### ISSUE TITLE
No Docker image for 8.8.1

### ISSUE THREAD

**Issue by ceeeekay** [elastic/package-registry#1041]
Hi there,

I'm running an air-gapped install using local Docker images for the package registry, and have an automated pull of the registry that matches the installed version of Elastic Stack.

As of today there is no 8.8.1 image available, which has broken my automation and resulted in no running containers.

Is this an oversight or has there been a decision to not match patch versions of Elastic Stack going forward?

Thanks :)

**Comment by mrodm** [comment]
Hi @ceeeekay , thanks for the heads up!

Docker images for 8.8.1 version are now available. Could you try again to run your automation?

**Comment by ceeeekay** [comment]
Hi @mrodm , looks good. Thanks!
