### ISSUE TITLE
Support search based on spec version

### ISSUE THREAD

**Issue by jsoriano** [elastic/package-registry#1050]
Add a new set of parameters to search packages based on their spec version:
* `spec.max`, maximum version supported by the client.
* `spec.min`, minimum version supported by the client.

If `spec.max` is defined, but `spec.min` and `kibana.version` are not, `spec.min` will be considered to be 3.0.

This will be used by Kibana to search packages on the range of spec version it supports.

**Comment by mrodm** [comment]
> If `spec.max` is defined, but `spec.min` and `kibana.version` are not, `spec.min` will be considered to be 3.0.

Related to this logic, to confirm if I got it correctly I have doubts about two scenarios @jsoriano:

- **First scenario**: `spec.max` and `kibana.version` are defined but `spec.min` is not defined:
    - could there be packages in the response with a spec (format_version) lower than `3.0.0` ? Not sure whether or not `3.0.0` should be used as minimum spec version.

- **Second scenario**: the three parameters are defined (`spec.min`, `spec.max` and `kibana.version`)
    - should all packages in the response should fulfilled all those conditions? or `kibana.version` should be dismissed if spec.* are in the query?
        - I would always filter by kbiana.version if that is in the query.
        - Thereby all packages should have the given `kibana.version` as condition and their format_version being in the range of `spec.min` and `spec.max`
