### ISSUE TITLE
/package endpoint not providing `owner.type`

### ISSUE THREAD

**Issue by ebeahan** [elastic/package-registry#1126]
https://github.com/elastic/package-registry/pull/1115 added `owner.type` and released in `v1.23.0`. However the field is still not included in ERP's response:

EPR prod version:

```
$ curl -sL https://epr.elastic.co/
{
  "service.name": "package-registry",
  "service.version": "1.23.0"
}
```

Searching for `1password`:

```
$ curl -sL https://epr.elastic.co/package/1password/1.26.0/ | jq '.owner'
{
  "github": "elastic/security-external-integrations"
}
```

**Comment by jsoriano** [comment]
Hey  @ebeahan, thanks for opening the issue. We are investigating the problem, everything seems to be fine with the package and the registry, but some index that the registry uses seems to be outdated, we are going to try to update it.

**Comment by jsoriano** [comment]
Issue fixed after reindexing the packages:
```
$ curl -sL https://epr.elastic.co/package/1password/1.26.0/ | jq '.owner'
{
  "type": "partner",
  "github": "elastic/security-external-integrations"
}
```
