### ISSUE TITLE
Add missing icons

### ISSUE THREAD

**Issue by jfsiii** [elastic/package-registry#119]
Currently only 5 ("auditd", "coredns", "iptables", "longdocs", "multiversion") or 17 packages have icons. The images the Manager is showing in the list view are from using some brittle logic to show the [icons from EUI ](https://elastic.github.io/eui/#/display/icons)

Many of these have icons as [`logo_*.svg` files in the EUI repo](https://github.com/elastic/eui/tree/master/src/components/icon/assets), ([`logo_apache.svg`](https://github.com/elastic/eui/blob/master/src/components/icon/assets/logo_apache.svg), [`logo_kibana.svg`](https://github.com/elastic/eui/blob/master/src/components/icon/assets/logo_kibana.svg), etc) which could be added to the package assets.

**Comment by ruflin** [comment]
Happy to add these icons to the packages so the logic can be removed on the manager side.

**Comment by ruflin** [comment]
Closing as icons were added in https://github.com/elastic/package-registry/pull/120
