### ISSUE TITLE
Add `/bin/bash` to the Elastic Package Registry Docker Image

### ISSUE THREAD

**Issue by linghengqian** [elastic/package-registry#1218]
- In https://discuss.elastic.co/t/why-doesnt-the-elastic-package-registry-docker-image-have-bin-bash/366138?u=linghengqian , I found that the Docker Image of `docker.elastic.co/package-registry/distribution:8.15.0` does not contain `/bin/bash`, but only `/bin/sh` and `/bin/ash`.
```shell
/package-registry # cat /etc/shells
/bin/sh
/bin/ash
```
- In contrast, `docker.elastic.co/beats/elastic-agent:8.15.0` and `docker.elastic.co/elasticsearch/elasticsearch:8.15.0` both have `/bin/bash`. This brings inconsistency in experience.
- It would be better if `/bin/bash` could be added to the Docker Image of Elastic Package Registry.

**Comment by jsoriano** [comment]
Hey, thanks for opening this discussion! I replied in discuss, let's continue there. I am closing this by now.
