### ISSUE TITLE
/package/auditd-2.0.4/docs/README.md is asciidoc file

### ISSUE THREAD

**Issue by jfsiii** [elastic/package-registry#124]
See https://github.com/elastic/integrations-registry/blob/master/dev/package-examples/auditd-2.0.4/docs/README.md 

I assume we should rename to something with an `.asciidoc` extension but perhaps we want to convert this to a markdown file? We can discuss options in our first ever EPM Weekly meeting.

**Comment by ruflin** [comment]
Yes, this should be converted to Markdown. It is `.asciidoc` as for now I just copied it over from the module. Will open a PR to convert it.

**Comment by ruflin** [comment]
Closing as this conversion happened.
