### ISSUE TITLE
[EPM] Add example package with lightweight module

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#125]

**Comment by ruflin** [comment]
@exekias @jsoriano Any recommendations on which one to use here best?

**Comment by jsoriano** [comment]
> @exekias @jsoriano Any recommendations on which one to use here best? Two ways forward: Take one and do an 80% implementation quickly or take one and do 100% which will make it release ready.

Tomcat may be a good one, that is quite complete, it has fields definition, dashboards and it doesn't have any native metricset.

**Comment by jsoriano** [comment]
AWS and Kafka packages are already migrated for first alpha (https://github.com/elastic/observability-dev/issues/723) and they use light modules, can this be closed?
Or the idea is to include the light module itself in the package?

**Comment by ruflin** [comment]
This can be closed. I opened this to see if there is anything special with the lightweight packages but as AWS and Kafka work, it does not seem to be the case.
