### ISSUE TITLE
[EPM] Tarballs are being served with a content-type of application/json

### ISSUE THREAD

**Issue by JoshMock** [elastic/package-registry#153]
Just noticed this while configuring the Fastly CDN in front of the prod instance: it looks like your your tarballs are being served with a `content-type: application/json` HTTP header when it should be `application/gzip`.

It's not breaking anything, but it might add some extra overhead to those requests when they pass through Fastly because it's going to try to gzip something that's already gzipped.

example:
```bash
$ curl -s --head https://epr.elastic.co/package/auditd-2.0.4.tar.gz | grep content-type
content-type: application/json
```

**Comment by ruflin** [comment]
Thanks for reporting this one. I opened a fix in https://github.com/elastic/package-registry/pull/154

**Comment by JoshMock** [comment]
Thanks @ruflin!

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/package-registry/pull/154 was merged.
