### ISSUE TITLE
Support query & filter

### ISSUE THREAD

**Issue by jfsiii** [elastic/package-registry#16]
From https://github.com/elastic/integrations-registry/pull/15#discussion_r291573657

Need a way to specify criteria to `/list` (e.g. things like text search on names, descriptions, kibana version ranges, license?, etc)

**Comment by ruflin** [comment]
I agree we will probably need all the feature you listed above. To scope this down, I would suggest we start with querying on the Elasticsearch / Kibana version. My current guess is that the basic query will be:

* Give me everything that is compatible with my current Kibana / Elasticsearch version? 

The assumption is made that Elasticsearch and Kibana always have to be on the same minor version. The query could then lookg as following:

* `/list?kibana=7.1.2`

Would that be enough to get started?

**Comment by jfsiii** [comment]
> Would that be enough to get started?

Definitely. `/list` only returns 2 packages right now so it's not an issue :)

I just figure we'll need something like it eventually. Feel free to ignore/delay until it's more pressing.

**Comment by ruflin** [comment]
I think we should start to get at least some basic logic into place to start playing around with it as it will be an important feature. Will start with what I proposed above.

**Comment by ruflin** [comment]
Part of making this more a search endpoint: https://github.com/elastic/integrations-registry/pull/57

**Comment by ruflin** [comment]
We support a variety of queries now. Closing.
