### ISSUE TITLE
Use a default name for main pipeline

### ISSUE THREAD

**Issue by exekias** [elastic/package-registry#183]
As discussed here: https://github.com/elastic/package-registry/pull/182#discussion_r358134199. It would be nice to have a default pipeline name so the package automatically uses that one if present. This way we don't need to link it from the manifest.

For example, if `default.json` pipeline is present, the package will install and use it as the default pipeline when routing ingested documents.

**Comment by ruflin** [comment]
What are we doing if `foo.json` exists but no `default.json` and no `ingest_pipeline` value is defined. Is that an invalid package?

**Comment by exekias** [comment]
I think so, unless we find a good reason to allow that, we could treat that as a broken package

**Comment by ruflin** [comment]
SGTM. Will add this as a "check" to validate a dataset.

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/package-registry/pull/188 was merged.
