### ISSUE TITLE
Support for specifying platforms in datasets

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#191]
Not all datasets work on all platforms or have different configurations per platform. A dataset must be able to have configurations specified per platform but also an entry on which platforms are supported.

**Comment by ruflin** [comment]
This should be done with constraints. @michalpristas currently works on constraints definitions for the agent and we should use the same syntax here.

**Comment by mtojek** [comment]
AFAIK we decided to go with different packages supporting different platforms (system vs windows vs linux). Resolving.
