### ISSUE TITLE
Versioning of the package registry API

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#204]
Currently there is no versioning of the package registry API. So far the API is pretty small but we need to decide if we should version it from day one or tackle the issue when have our first breaking changes.

**Comment by jfsiii** [comment]
From day one, or as early as possible, IMO.

We know the changes will occur; we might as well have a plan for how to handle it. We can default to v1/whatever to reduce burden on the user, but we should have some way to support versions.

**Comment by ruflin** [comment]
Labeling this `beta1` as we need to come to a conclusion by then if we do it or not.

**Comment by jfsiii** [comment]
I think https://apisyouwonthate.com/blog/api-versioning-has-no-right-way does a good job summarizing our options and the tradeoffs but most results for "API versioning strategy" will give a similar list.

We're already doing Global API Versioning using subdomains (`https://epr.elastic.co/`, `https://epr-experimental.elastic.co/`) and #560 explores the `/v1` path-based approach (but only for some routes).

It's also possible we could expand on the OpenAPI work started in https://github.com/elastic/package-registry/pull/490 and go for the ['commit to contracts'](https://apisyouwonthate.com/blog/commit-to-api-contracts) approach linked in that article. That's more flexible with less churn but would take longer to setup than global versioning.

I think my "anything is possible" ranked preferences are

1. Contracts via OpenAPI
2. global versioning via subdomain
3. global versioning via path
4. resource versioning

but different subdomains is very attractive and might actually be my first choice. Especially if we combine it with (2) by, say, publishing the OpenAPI spec from a known route on each domain.

**Comment by jfsiii** [comment]
After the challenges listed at https://github.com/elastic/package-registry/pull/560#issuecomment-651955920 it seems relevant to mention the option of not using versions and only making backwards compatible changes

There's a good article on it at  https://apisyouwonthate.com/blog/api-evolution-for-rest-http-apis

This is the basic approach I've used at a few jobs. It puts more burden the API authors but keeps things simple for clients and consumers.

**Comment by ruflin** [comment]
I closed https://github.com/elastic/package-registry/pull/560 for now and we stick with what we have at the moment.

I think it will be important that we properly use the manifest file `format_version` to indicate changes and also always send the Kibana version in the headers of all requests. This will make sure we could also make decision on this Kibana version if needed. Note: This does not replace the query param to the /search endpoint @ph Could you follow up on this.

**Comment by jfsiii** [comment]
> and also always send the Kibana version in the headers of all requests

@ruflin Can you say more about this? `kbn-version` or another header? 

The `kbn-version` is sent with any request from Kibana but, in my understanding, the registry hasn't used required/used it. Is whatever header optional or required for all clients? 

Is it correct that, combining that with https://github.com/elastic/kibana/issues/64868#issuecomment-637574876 means /search accepts a query param and the header?

**Comment by ruflin** [comment]
@jfsiii `kbn-version` sounds to be good here. Didn't know it is already sent.

What I have in mind is that in some cases we might adjust the output format based on the Kibana header we get. So in 7.9 we have the field  `foo` in the JSON output and for 7.10 it is `bar`. It allows us internally in the registry to keep backward compatiblity with older versions.

For `/search`: This will only support the query param. The header should still be sent but will not effect what we query on. It might effect the output format.

**Comment by jfsiii** [comment]
@ruflin yep, I mentioned it in that same search issue.

Sounds like we're now discussing versioning via header. I'm fine with this approach as well but it's important to document the different responses (e.g. 7.9 gets `foo` & 7.10 gets `bar`) from your example.

**Comment by ruflin** [comment]
@jfsiii My hopes are we don't have to, but if we, yes we need to document well. I also plan to spend some time after 7.9 to properly document packages etc.

**Comment by jfsiii** [comment]
When/if we go that way, we may want to use `Accept` & mime-types versus a custom header. 

This is how GitHub https://docs.github.com/en/rest/overview/media-types#request-specific-version and a few others do it. 

It's also supported by OpenAPI and I am not sure kbn-header would be

**Comment by mtojek** [comment]
I think we can close this issue and just keep in mind, that if we expand to more endpoints than `/search`, it will be a good option to introduce the API version.
