### ISSUE TITLE
Add Docker image build stage

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/package-registry#205]
We have a new namespace in place to publish the Docker images, thus we have to add a new stage to the pipeline job to build and publish the docker images. We will tag the image with the latest version plus the word SNAPSHOT, something like `docker.elastic.co/package-registry/package-registry:0.2.0-SNAPSHOT` also we store the same image with a tag referenced the commit, something like `docker.elastic.co/package-registry/package-registry:f999b7a84d977cd19a379f0cec802aa1ef7ca379`, finally, for GitHub tags we will use the GitHub tag and the commit to publish the Docker image, something like `docker.elastic.co/package-registry/package-registry:0.2.0` and `docker.elastic.co/package-registry/package-registry: 928f750f7dace1934dc5a67bfe24eb848ca44be1 `

```
docker build .
docker tag 87e1feeff7c8 push.docker.elastic.co/package-registry/package-registry:0.2.0
docker push push.docker.elastic.co/package-registry/package-registry:0.2.0
```

**Comment by JoshMock** [comment]
We have plenty of examples for how to [log in and push Docker images](https://github.com/elastic/infra/blob/master/.ci/templates/elastic+infra+master+docker-image.yml) to our registry using Vault approles to pull a machine user's password. 

We can either give an existing machine user permission to the `package-registry` namespace, or we can create a new machine user just for this purpose. 

What Jenkins instance is all this running in? That may make it easier to determine what all is needed from Infra's side of things.

**Comment by kuisathaverat** [comment]
we do it  on a daily basis, so we are fine we do not need to modify anything on the workers

https://github.com/elastic/apm-pipeline-library/blob/master/.ci/buildBeatsDockerImages.groovy
https://github.com/elastic/apm-pipeline-library/blob/master/.ci/buildDockerImages.groovy
https://github.com/elastic/apm-pipeline-library/blob/master/.ci/dockerImagesOpbeans.groovy
https://github.com/elastic/apm-pipeline-library/blob/master/vars/opbeansPipeline.groovy

**Comment by JoshMock** [comment]
That secret `secret/apm-team/ci/docker-registry/prod` stores credentials for the `apmci` user. If you want to keep using those same credentials, that's fine! We just need to give `apmci` push access to the `package-registry` namespace; right now it only has push access to the following namespaces:

- `integrations-ci`
- `observability`
- `observability-ci`

Let me know if that's what you need and I'll make the necessary permissions change.

**Comment by kuisathaverat** [comment]
@JoshMock we've requested a new user to use it across Observability https://github.com/elastic/infra/issues/17661

**Comment by ruflin** [comment]
@kuisathaverat Will you need anything here from my end to move this forward?

**Comment by kuisathaverat** [comment]
We have the new user to push the images, we will implement it in the next days
