### ISSUE TITLE
Rename ingest pipelines in packages

### ISSUE THREAD

**Issue by skh** [elastic/package-registry#208]
Currently, EPM installs ingest pipelines when data sources are created. In this step, it also rewrites references to pipelines within other pipelines.

Now that data sources cease to exist, ingest pipelines in a package can be given the exact name the will have after installation, and EPM will not need to parse and rewrite them. This will overall simplify things.

**Comment by neptunian** [comment]
It was decided that we would not rename in the package, but keep the logic in the EPM side.
