### ISSUE TITLE
Remove index patterns from packages, if necessary

### ISSUE THREAD

**Issue by skh** [elastic/package-registry#209]
Currently EPM generates the index patterns `metrics-*` and `logs-*` from `fields.yml` files contained in all installed packages.

In addition to that, some packages contain pre-generated index patterns. One example is: https://github.com/elastic/package-registry/blob/master/dev/package-examples/auditd-2.0.4/kibana/index-pattern/auditbeat-*.json

This task is to
* decide if additional index patterns are supported in packages
* if yes, document their use
* if no, remove them from packages and ASSETS.md

**Comment by ruflin** [comment]
At the moment I don't see a reason to support index patterns. Lets remove support for it and wait for a feature request. @skh Could you take care of this?
