### ISSUE TITLE
Create docs on how to build a package

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#220]

**Comment by ruflin** [comment]
@mtojek Assigned this to you as I think as part of your work on the script and building packages, this will probably be part of the output. It is a great way to share with the other devs some notes on what to do.

@exekias FYI

**Comment by mtojek** [comment]
@ruflin I think we already have a README file with basic instructions: https://github.com/elastic/package-registry/blob/master/dev/import-beats/README.md

Are there any parts you'd like me to describe thoroughly?

**Comment by ruflin** [comment]
@mtojek I think the README only covers how to run the script but no details about how a package is actually built. What assets are inside, what is in the manifest etc. You built up all this knowledge during building the script but new devs starting to build packages will miss this knowledge. This docs should be really about onboarding new devs to build packages as quickly as possible.

**Comment by exekias** [comment]
Where do you plan to put these docs @ruflin ?

**Comment by exekias** [comment]
My understanding is that we need several docs:

 - A package format reference, that should be part of the docs around how the registry works, and should be updated with every change we do to the format. This would be development agnostic, only focused on the format: what's mandatory/optional, field definitions, etc

 - A different doc focused on how to develop an integration, right now we still need to work on how this will be done, part of it should, of course, be the documentation.

Are we talking here about the first point?

**Comment by ruflin** [comment]
@exekias Agree, there are both parts. Part 1 is basically the spec and should go into this registry. Part two about how to build a package I would put first here but should be moved into where the packages are in the future, so probably https://github.com/elastic/integrations

In this issue I was more thinking about 2, part of 1 I hope is https://github.com/elastic/package-registry/tree/master/dev/packages/example/reference-1.0.0 and the existing nginx / coredns package but we will need more obviously. Basically examples as docs for now.

**Comment by mtojek** [comment]
I'm going with the onboarding: https://github.com/mtojek/package-registry/blob/how-to-build-package/ONBOARDING.md

This would be beneficial for Integrations team members.

**Comment by mtojek** [comment]
@ruflin 

Based on current docs status, do you see a need for any additional section/document or can we close this issue?

**Comment by ruflin** [comment]
@mtojek Lets close this. More docs will be needed but I expect this to be an iterative team effort from here on.
