### ISSUE TITLE
Add final pipeline to base package

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#225]
The current idea is that all events will flow through a [final pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules.html#dynamic-index-settings). This pipeline needs to be defined and set on each template with the `index.final_pipeline` setting.

This final pipeline should be part of the base package and can be empty at first.

**Comment by ruflin** [comment]
Work is ongoing to add a final pipeline to Beats here: https://github.com/elastic/beats/pull/14001

**Comment by ph** [comment]
@ruflin We need that for b1 to trace events coming from agents and endpoint.

**Comment by ruflin** [comment]
@ph How takes a lead on defining this final pipeline? If we want to have it on all events, it must be shipped by Elasticsearch.

**Comment by ph** [comment]
Will take a stab at it. 

cc @dakrone for FYI.

**Comment by dakrone** [comment]
@ruflin @ph I thought our original consensus was to skip a pipeline for now, since we don't have a need yet? Is this something necessary to add to the default bundled templates in https://github.com/elastic/elasticsearch/pull/57629 ?

**Comment by ruflin** [comment]
@dakrone I must confess i forgot about the final pipeline. I suggest we get your PR in without it and figure out if we need it later. An option here is also that only if ingest manager updates the base package, the pipeline exists.

**Comment by ph** [comment]
Lets sync up with endpoint if this is a requirement.

**Comment by mtojek** [comment]
I think we can resolve this issue now. We don't have the base package.
