### ISSUE TITLE
Prepare migration plan for module docs

### ISSUE THREAD

**Issue by mtojek** [elastic/package-registry#262]
The PR https://github.com/elastic/package-registry/pull/261 introduces basic stub for README.md . The goal of this task is to assemble a list of actions to build/rewrite existing Beats docs for packages.

Existing Beats docs refer to either metricbeat (metrics) or filebeat (logs). It's hard to combine them automatically without preserving the original division (into beats). Also, some of beats modules already contain README.md, mainly for developers/contributors. 

Issue: https://github.com/elastic/package-registry/issues/221

/cc @ruflin

**Comment by mtojek** [comment]
There are a couple of options:

1. Parse output HTML code that is published online, merge metricbeat and filebeat sections.

2. Convert .asciidoc to docbook, and then to Markdown, but the migration quality will be poor, also merge metricbeat and filebeat sections.

3. Manually rewrite docs per integration. We can define a common template for .md files (e.g. README.md).

**Comment by ruflin** [comment]
I think our path forward here is option 3 as too many changes are need. One thing that would be still nice to have is that all the content is copied over already to the README.md file from the existing docs. This will help review and reorganise all the content.

**Comment by mtojek** [comment]
I think, this one can be closed. Further plans are discussed in: https://github.com/elastic/integrations/issues/20
