### ISSUE TITLE
import-beats: set 'release' fields

### ISSUE THREAD

**Issue by mtojek** [elastic/package-registry#277]
Generated packages should have `release` fields provided.

A `release` field may have different values for single metricsets and module (e.g. new metricset can be released as beta.

**Comment by ruflin** [comment]
This info should be available for each module and fileset / metricset in the fields.yml today. I wonder if we have a case where the release status of the filebeat vs metricbeat module is not identical 🤔

**Comment by mtojek** [comment]
Merged, resolving.
