### ISSUE TITLE
Remove Makefile and replace through mage commands

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#309]
We currently have a Makefile and a magefile in the package registry repository: https://github.com/elastic/package-registry/blob/master/Makefile We should only have the magefile to keep things simple. 

To complete this issue, the Makefile should be remove and the commands transitioned to the magefile. As part of this it should be made sure that the places where these commands are used are updated.

**Comment by mtojek** [comment]
Makefile doesn't exist anymore. Resolving.
