### ISSUE TITLE
Use stream.dataset instead of event.dataset

### ISSUE THREAD

**Issue by mtojek** [elastic/package-registry#315]
Reported in https://github.com/elastic/package-registry/pull/313

>@mtojek An other thing that just came to my mind is that as part of the migration we should also start thinking about optimising the dashboards. For example the query for event.dataset should become a query for stream.dataset which is a constant keyword and much more efficient. The gent should always add these fields (@michalpristas will know more if this already happens).
I don't think we need to do all these optimisations directly during the migration but could be done later on. But we should start a checklist with these already now so we don't forget.

**Comment by michalpristas** [comment]
just a small note, agent provides information about dataset to corresponding beats but whether or how they are used or injected into events is up to beat itself. agent does not enrich any event coming from beat.

**Comment by ruflin** [comment]
@michalpristas @ph Even though events are not sent through the agent, my understanding is that it is up to the agent to ensure that the stream fields and correct index are set: https://github.com/elastic/beats/issues/16562

**Comment by michalpristas** [comment]
correct index is something we have now. i dont' think we inject these 2 fields separately and that input on the beat side knows to pick them up and inject. 
or is the issue meant in a way that agent will generate add_fields processor out of these fields?

**Comment by ruflin** [comment]
@michalpristas Lets take this to a separate issue.

**Comment by mtojek** [comment]
> @michalpristas Lets take this to a separate issue.

Could you please link it here? I'm not sure if I can proceed with issue or not yet.

**Comment by mtojek** [comment]
I converted this into general issue as I don't see `stream.dataset` in collected documents.

**Comment by ruflin** [comment]
@michalpristas Can you investigate this? ^

**Comment by michalpristas** [comment]
have this as part of each beat configuration (with according values) will take a look though
```
processors:
      - add_fields:
          fields:
            stream.type: logs
            stream.dataset: generic
            stream.namespace: default
```

**Comment by michalpristas** [comment]
I see them here under fields:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/1522652/79845995-28d08300-83be-11ea-89a1-2b2e45e2d50c.png">

**Comment by ruflin** [comment]
@michalpristas They must be on the top level and not under `fields`!

**Comment by michalpristas** [comment]
let me check what i can do about it, i hope this is not the default behavior of the processor

**Comment by michalpristas** [comment]
PR here: https://github.com/elastic/beats/pull/17858

**Comment by ruflin** [comment]
Closing as by now we landed by `dataset.name`.
