### ISSUE TITLE
MySQL integration: run the full setup

### ISSUE THREAD

**Issue by mtojek** [elastic/package-registry#320]
Run the agent code, select MySQL integration to install and test it.

**Comment by mtojek** [comment]
First spotting: to build an agent, I need to install full Xcode (`xcodebuild`) and to do that, I need to upgrade Mac OSX.

**Comment by ruflin** [comment]
Wow, I didn't expect this. Which OS X version are you on?

**Comment by ruflin** [comment]
@michalpristas Where are we standing with having an easy test setup available? Also we should find a way that users don't have to run the full packaging to just use the agent binary.

@mtojek I hope as soon as we have snapshot builds available, all this becomes obsolete. Perhaps as an intermediary solution, we could just have link to a current binary we keep updating?

**Comment by michalpristas** [comment]
@ruflin in PR here: https://github.com/elastic/beats/pull/17312

**Comment by michalpristas** [comment]
agent binary is fine but we still need correct beats to work properly, the thing in PR is a limited version of packaging which builds only linux bits and has a check for existing image in image to speed it up
