### ISSUE TITLE
manifest: add support for path variables

### ISSUE THREAD

**Issue by mtojek** [elastic/package-registry#325]
Some configuration files may use path variables:

```
    os.darwin:
      default:
      - /usr/local/var/mysql/{{.builtin.hostname}}.{{.builtin.domain}}.err*
```

The only workaround at the moment is to set a sample value or skip the entire line.

**Comment by ruflin** [comment]
This depends on https://github.com/elastic/beats/issues/17340

**Comment by ruflin** [comment]
Dynamic inputs should solve this issue: https://github.com/elastic/beats/issues/19225

**Comment by ruflin** [comment]
Closing this issue as I think it is not a problem of the package-registry anymore to solve this and potentially not even of the package-spec as it is directly part of the input definition. Will follow up in the right repo if needed.
