### ISSUE TITLE
prometheus/collector: conflicting name

### ISSUE THREAD

**Issue by mtojek** [elastic/package-registry#336]
I've just spotted that there is a naming conflict in Beats:
- `x-pack/metricbeat/prometheus/collector`
- `metricbeat/prometheus/collector`

These modules datasets are related to different features:
https://github.com/elastic/beats/tree/master/metricbeat/module/prometheus/collector
https://github.com/elastic/beats/tree/master/x-pack/metricbeat/module/prometheus/collector

**Comment by ruflin** [comment]
@exekias Can you elaborate on how the two are related? Do we need both? Is one a (future) input?

**Comment by exekias** [comment]
They are pretty similar (and share part of the implementation), the difference is that the x-pack version makes use of `histogram` field in ES, which is only available in basic.

As the agent will be basic we only care about the x-pack implementation there. I would suggest that the script goes over OSS first and overrides any collision with what's found in x-pack maybe?

**Comment by ruflin** [comment]
++, or we have a blacklist that we don't want to convert as this seems to be only one we need magic. Whatever is easier to implement.
