### ISSUE TITLE
Document field description format

### ISSUE THREAD

**Issue by skh** [elastic/package-registry#340]
Packages may contain fields definitions in YAML files in `dataset/DATASETNAME/fields/` directories. These files are used by EPM to generate elasticsearch index templates and kibana index patterns. The format of these files comes from the `beats` project, but has never been documented.

This task is to document this format in this repository.

**Comment by mtojek** [comment]
I know that it's not a fully defined schema, but I've recently defined a structure for a single field (for serialization purposes): https://github.com/elastic/package-registry/blob/master/dev/import-beats/fields.go#L21

**Comment by ruflin** [comment]
@skh You might be able to copy some parts from here: https://github.com/elastic/beats/pull/12505

**Comment by mtojek** [comment]
We have the package-spec now and these files are also covered. Resolving.
