### ISSUE TITLE
Move packages to its own repository

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#347]
Today the packages are in the same repository as the registry itself for ease of development. We need to decouple the package development for the registry development. Because of this, packages must be moved to its own repository. My suggestion for the packages we currently have is that they are moved to the integrations repository: https://github.com/elastic/integrations

Moving the packages will mean we need to adjust the building step of the Docker image to still pull in all the packages, validate them and build the container.

Overall this will probably have other side effects for example that the package validation script should be available as binary (or similar) in the integrations repo for validation.

**Comment by ruflin** [comment]
@mtojek FYI, something we should do in the near future.

**Comment by exekias** [comment]
I would hope we can leave tooling outside of the integrations repo. @mtojek is working on a proposal for the development process and cli, perhaps this validation could be part of that tooling?

**Comment by mtojek** [comment]
I haven't started works on the proposal yet. I assume this will also affect all our docs.

**Comment by ph** [comment]
This look like the same issue as https://github.com/elastic/package-registry/issues/447 assigned to @mtojek, @ruflin  I think we can close this one?

**Comment by ruflin** [comment]
Yes, closing.
