### ISSUE TITLE
Discuss: Where should the datasource summary happen?

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#348]
To make building the Data Source UI page easier, we pregenerate a `datasources` entry as part of the the `index.json` in each package. This information is an aggregation from the package and dataset manifests and duplicates quite a bit of data.

The above works at the moment but we should have a discussion if long term having the datasources array in the index.json is the right place. All the other data in the file is just consumed from the manifest files. Removing it would simplify the generation code in the registry and clean up the output.

Few places this could go:

* Have a separate `/datasource.json` files. This would separate the concerns of having just the info available and having aggregated info for building the UI.
* Build it in Kibana: With this, Kibana would responsible to build up this array. The disadvantage is that each Kibana instance would have to do it instead of once in a single place. The advantage is that if there is a better format in the future on how to summarise it, Kibana can directly own it without having a breaking change in the registry.

No immediate change needed right now, this is to start a discussion.

**Comment by mtojek** [comment]
I appreciate the discussion we had the today morning. I support the idea of separating concerns. My overview is rather radical - the package as bundle shouldn't depend on the UI or should have contain any extra properties, or rather workarounds, to support the rendering.

I would split the whole concept into two parts:
1. Package manifests and references artifacts (zipped bundle).
2. Processed package contents, built from results of (1).

I understand the idea of not introducing advanced configuration processing into Kibana, but actually it's all for Kibana. I would do step forward:

3. Prepare an optimized, tuned bundle/index.json/minified in the best format acceptable by Kibana.

> Kibana can directly own it without having a breaking change in the registry.

This is actually an important argument. Kibana team can adjust the rendering without rebuilding any package content.

**Comment by ruflin** [comment]
Taking the above one step further, it could be argued that the `index.json` shouldn't be in the `.tar.gz` at all (today it is). I think it is valuable to have it in the running registry service but I would challenge if it is useful in the .tar.gz.

**Comment by ruflin** [comment]
My take away from the above discussion so far is that the summary must happen on the Kibana side, especially as in the future users might be able to upload packages directly to Kibana. I'll follow up with a Kibana issue.

**Comment by ruflin** [comment]
Here is the Kibana follow up issue: https://github.com/elastic/kibana/issues/66214 I'm closing this issue as it is expected a new issue will be opened in the registry as soon as the change is made in Kibana.
