### ISSUE TITLE
Support limiting number of data sources

### ISSUE THREAD

**Issue by jen-huang** [elastic/package-registry#350]
For some packages like Endpoint, agent configs can only support 1 data source from that package. Those restricted data source definitions should have a property to flag that for down stream consumers.

Property name ideas:
`no_conflict: boolean` (if true, up to 1 of same data source)
`no_duplicate: boolean` (same as above)
`self_limit: number` (if specified, up to the limit value of same data source)

(...naming is hard 😅)

**Comment by ruflin** [comment]
What about `multiple: false`? I would prefer we stick with a boolean for now as I don't see a use case where we would say 42 are possible.

**Comment by jen-huang** [comment]
+1 on that naming and boolean @ruflin

**Comment by ruflin** [comment]
I opened https://github.com/elastic/package-registry/pull/361 for this
