### ISSUE TITLE
System module not OS specific

### ISSUE THREAD

**Issue by 111andre111** [elastic/package-registry#369]
Fleet Manager can roll out Elastic Agent on Windows, MacOS or Linux specific.
But the resulting Module Package configuration I see is not OS specific.\

For Linux it rolls out the stream id `logs-system.auth` with Log files `/var/log/auth.log*, /var/log/secure*` and a second stream called `logs-system.syslog` with `/var/log/messages*, /var/log/syslog*`which is appropriate for Linux.
For MacOS it should change the `logs-system.syslog` to `/var/log/system.log*, /var/log/install.log*, /var/log/wifi.log*`. I didn't find an appropriate set for `/var/log/auth.log` for MacOS. Normally you would open Console App or execute command `log show` to find such things out.
So to be checked here.
For Windows it should not take these file sets at all and alternatively install winlogbeat
and take for the syslog part the System event log and for the auth part the `Security` event log.

**Comment by 111andre111** [comment]
Maybe that needs an appropriate issue in the Fleet Manager kibana repo too?

**Comment by 111andre111** [comment]
But I think for Windows there is the windows stream, so it just would be appropriate, if only for Windows systems the log config would not be configured on these systems.

**Comment by ruflin** [comment]
We don't support this in our in our initial release but plan to add support for multi OS support later on. Removing the bug label.

**Comment by mtojek** [comment]
We have packages targetting different platforms: Windows, Linux or generic system. We can resolve this issue now.
