### ISSUE TITLE
Adjust config options and naming for template.*

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#394]
In https://github.com/elastic/package-registry/pull/346#discussion_r408631880 a template_path was introduced but is not the optimal name. This issue is to follow up on this conversation and implement potential changes.

**Comment by ruflin** [comment]
As we got rid of template_content we could go back to just call this `template`. At the same time I would like to have some unified naming on path / src etc. across the manifest. @mtojek @ph @ycombinator Feedback welcome.

**Comment by ruflin** [comment]
@mtojek @ycombinator WDYT, should be keep the name `template_path` as is or change it? To not introduce any breaking changes, I would probably just keep it for now and close this.

**Comment by mtojek** [comment]
IMHO the `template_path` is more descriptive than `template`.

**Comment by ruflin** [comment]
Closing for now, please reopen if someone disagrees.
