### ISSUE TITLE
Nginx error log paths is not multi

### ISSUE THREAD

**Issue by jen-huang** [elastic/package-registry#403]
https://epr.ea-web.elastic.dev/package/nginx/0.0.2

Nginx error log paths has multi: false, causing Kibana to show simple text input instead of combo box input like access log paths:

![image](https://user-images.githubusercontent.com/1965714/80547747-dcf97d00-896d-11ea-9014-337ec1d7204e.png)

```
              "vars": [
                {
                  "name": "paths",
                  "type": "",
                  "multi": false,
                  "required": true,
                  "show_user": false,
                  "default": [
                    "/var/log/nginx/error.log*"
                  ],
                  "os": {
                    "darwin": [
                      "/usr/local/var/log/nginx/error.log*"
                    ],
                    "windows": [
                      "c:/programdata/nginx/logs/error.log*"
                    ]
                  }
                }
```

**Comment by mtojek** [comment]
If it's not urgent, can we wait for the https://github.com/elastic/package-registry/pull/379 get merged? I'm fine-tuning the package manually and the field property (multi) there is correct.
