### ISSUE TITLE
Validate ingest pipelines in YAML format

### ISSUE THREAD

**Issue by skh** [elastic/package-registry#404]
EPM installs ingest pipelines in YAML format as they come with the package. Elasticsearch only accepts ingest pipelines that start with `---` on a separate line. Therefore, pipelines that can be installed with `libbeat` can't be installed with EPM. This leads to issues like https://github.com/elastic/kibana/issues/63726

This task is to add validation for YAML-format pipelines so all problems can be detected when packages are built.

**Comment by mtojek** [comment]
@skh @ruflin 

I assume that the validation should be present on both sides. Does Kibana fail with HTTP 400 with a descriptive message for invalid YAML files?

**Comment by skh** [comment]
> Does Kibana fail with HTTP 400 with a descriptive message for invalid YAML files?

Not at the moment, but I've added https://github.com/elastic/kibana/issues/64739.

**Comment by mtojek** [comment]
I started looking into this issue and identified a couple of placeholders that need a default value.

Re `{< IngestPipeline "pipeline-plaintext" >}`:

@skh What would be the pipeline name used by the Ingest Manager? In beats it was: `filebeat-5.2.0-nginx-access-pipeline`

Re...
 ```
- rename:
      field: cisco.{< .internal_prefix >}.list_id
      target_field: cisco.{< .internal_prefix >}.rule_name
      ignore_missing: true
```

... and...
```
 - drop:
      if: "ctx.event.severity > {< .log_level >}"
```
To let validation pass, I can temporarily use a "fix-me" value.

Re:
```
    {<if .use_namespace >}
    {
      "script": {
        "lang": "painless",
        "source": "def dict = ['result': new HashMap()]; for (entry in ctx['json'].entrySet()) { dict['result'][entry.getKey()] = entry.getValue(); } ctx['osquery'] = dict; ctx.remove('json');"
      }
    },
    {< end >}
```

I can temporarily remove the condition.

**Comment by ruflin** [comment]
I think the only templating we should support in the pipelines is referencing an other pipeline. Everything else should not be supported anymore. I assume `{< .log_level >}` is something that Beats replaces today? Or how does this work?

**Comment by skh** [comment]
We currently don't rename index pipelines during package installation, so when we find `{< IngestPipeline "pipeline-plaintext" >}` we assume that there is a `pipeline-json.{json,yml}` pipeline in the same directory and insert a reference to it. We use the filename of the pipeline in the package as the pipeline name, minus the extension.

That happens around here: https://github.com/elastic/kibana/blob/master/x-pack/plugins/ingest_manager/server/services/epm/elasticsearch/ingest_pipeline/install.ts#L101-L113 and the rewriting is really just a regular expression here: https://github.com/elastic/kibana/blob/master/x-pack/plugins/ingest_manager/server/services/epm/elasticsearch/ingest_pipeline/install.ts#L53-L59

This doesn't mean we won't support real templating at some point, just that at the time of implementation we didn't know if we need it at all.

**Comment by mtojek** [comment]
> We use the filename of the pipeline in the package as the pipeline name, minus the extension.

@skh what if there are multiple integrations with the same pipeline name? Does Kibana understand the package scope?

**Comment by mtojek** [comment]
@ruflin

See:
/Users/marcin.tojek/go/src/github.com/elastic/beats/x-pack/filebeat/build/package/module/cisco/shared/ingest/asa-ftd-pipeline.yml

```
  - rename:
      field: _temp_.cisco
      target_field: "cisco.{< .internal_prefix >}"
      ignore_failure: true
```

```
  - drop:
      if: "ctx.event.severity > {< .log_level >}"
```

> Ingest pipelines are prefixed by type and dataset name, so there can't be a conflict
Which part of the whole solution does perform naming? AFAIK in Beats it was in the template function in Beats.

**Comment by skh** [comment]
> what if there are multiple integrations with the same pipeline name? Does Kibana understand the package scope?

@mtojek Apologies, my description was incomplete. The full pipeline name is put together here: https://github.com/elastic/kibana/blob/b140ad7194338610b791750001730279a4806ecc/x-pack/plugins/ingest_manager/server/services/epm/elasticsearch/ingest_pipeline/install.ts#L193 and ends up being
```
TYPE-PACKAGE_NAME.DATASET-PACKAGE_VERSION-PIPELINE_NAME
```
with `TYPE` currently being `logs` or `metrics`, and `PIPELINE_NAME` the filename without the extension, as explained above.

**Comment by skh** [comment]
Also, for completenes the pipeline referenced in the dataset `manifest.yml` is just called
```
TYPE-PACKAGE_NAME.DATASET-PACKAGE_VERSION
```
, only the referenced pipelines get the pipeline filename as a suffix.

**Comment by mtojek** [comment]
If I leave the template function "IngestPipeline" it will fail because of unescaped " ":

```
          "pipeline": {
              "name": "{< IngestPipeline "azure-shared-pipeline" >}"
          }
```

**Comment by skh** [comment]
Can you do the validation with a temporary pipeline where you did the replacing or would that be too much overhead?

**Comment by mtojek** [comment]
I think I can simply skip all "IngestPipeline" template functions during validation. Otherwise we should find other way or defining a reference to other pipeline (something compliant with the schema).

**Comment by skh** [comment]
Would 
```
"pipeline": {
              "name": "{< IngestPipeline 'azure-shared-pipeline' >}"
          }
```
work? (Note the single quotes.)

**Comment by ruflin** [comment]
@mtojek @andrewkroh Pipelines which are config based we can't really support in the future, for example https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml#L62 I even wonder how this worked today if 2 Beats had a different config?

**Comment by ruflin** [comment]
@mtojek +1 to simplify things to just skip everything that is looking exactly like this one here: `https://github.com/elastic/package-registry/blob/master/dev/packages/example/coredns/0.0.2/dataset/log/elasticsearch/ingest-pipeline/pipeline-entry.json#L13 The others with `{<`  should not exist in the package / are not supported. Correct @skh ?

**Comment by skh** [comment]
We support both `{{...}}` and `{<...>}` as delimiters and both `"..."` and `'...'` as inner quotes.

**Comment by andrewkroh** [comment]
> Pipelines which are config based we can't really support in the future, for example https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml#L62 I even wonder how this worked today if 2 Beats had a different config?

I think there are three use cases for templating in ingest pipelines in Filebeat today.

- Referencing other pipelines in the same module.
- Feature inclusion based on Elasticsearch version.
  - This way a module can be written once and work with multiple ES versions. We have used this when processor parameters changed between versions. And also to be able to use new processors if they exist in the ES version.
- Configurable behavior like "drop if severity > $log_level"
  - It not a problem to drop support for this IMO. It's was rarely used. And as you mentioned would be wierd if it was used twice with different config (first one to install their pipeline would win).

**Comment by ruflin** [comment]
@skh I don't remember the reason why we supported both. Now that we use handlebars also in other places we should limit it to one and probably `{{`?

@andrewkroh 
* Referencing other pipeline: This is still supported (inside the same dataset)
* This is solved by having a "required ES version" in each package. If you need this feature, you basically have 2 packages released with different dependencies
* Configurable behaviour: Yes, this we can't support anymore. @andrewkroh Can you check with the team on how to work around these in the pipelines?

**Comment by skh** [comment]
> I don't remember the reason why we supported both.

We wanted to support existing pipelines from *beats modules.

**Comment by ruflin** [comment]
@skh I suggest we drop this support and only support `{{`. The script from @mtojek + https://github.com/elastic/package-registry/pull/423 should solve this.

**Comment by ruflin** [comment]
I had a follow up chat with @skh What we have in the ingest pipelines today is not necessarly valid handelbards as we only use regexp replacing on the Kibana side. I'll open an issue to discuss this further.

More important in the context here is I think that moving forward there is only 1 valid syntax and that it is valid YAML.

**Comment by andrewkroh** [comment]
I found a fourth way in which variables are used in Ingest Pipelines. The Cisco module uses a variable to be able to the share code for a pipeline ([example](https://github.com/elastic/beats/blob/ae1125d0cd8bc7b0ffe09953dfb3a83105ea3235/x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml#L1257)). The same file is used to create two separate Ingest Node pipelines in Elasticsearch. The variable is the name of the fileset. And it is used to namespace some data in pipeline (like `target_field: cisco.{{ fileset }}.rule_name`). 

Is this something that we can support? Like maybe inject variables for the module name and fileset (not sure I'm using the right terminology for that piece). Otherwise we can duplicate pipeline code that is shared now.

> Configurable behaviour: Yes, this we can't support anymore. @andrewkroh Can you check with the team on how to work around these in the pipelines?

This is used in two modules - osquery and cisco. In both cases we can drop this configuration option and just not support it. osquery uses it to control the data's target namespace - we'll just hardcode that to `osquery.log`. And cisco uses it to drop data below a configurable log level (so no more dropped events)

**Comment by ruflin** [comment]
For shared pipelines I think there are two "futures":

* Short term: Something that should be implemented by the developer of packages as their build scripts. Basically support variables in a local repo but when `build` is run it duplicates it and builds 2 final pipelines. The package itself does not support it
* Long term: Packages support to reuse pipelines. Not sure how it will exactly work but I think there are other places where this can become useful.

What can always be done is inject some data into the event to make the decision in the ingest pipeline if that is possible.

**Comment by mtojek** [comment]
Resolving in favor of https://github.com/elastic/package-spec/issues/89
