### ISSUE TITLE
stages in packages don't seem to be in sync

### ISSUE THREAD

**Issue by 111andre111** [elastic/package-registry#408]
Maybe this is an impression only, but it seems like changes that are applied to the certain package stages don't seem to be synchronized. Let me try to explain what I mean:
  https://github.com/elastic/package-registry/tree/master/dev/packages/example
  https://github.com/elastic/package-registry/tree/master/dev/packages/beats
  https://github.com/elastic/package-registry/tree/master/dev/packages/alpha

So for example:
This manifest file which is older:
  https://github.com/elastic/package-registry/blob/master/dev/packages/beats/system/0.0.1/dataset/auth/manifest.yml
Seems to have more modern approaches than the repo file here:
  https://github.com/elastic/package-registry/blob/master/dev/packages/example/system/0.0.2/dataset/auth/manifest.yml

It looks like there is an OS dependent way if describing paths, which isn't reflected in the example part.

Is there a way of reviewing these 3 "branches" about such change topics?

**Comment by ruflin** [comment]
@111andre111 We are currently in the processes of updating all these packages to make them ready for release. The 0.0.1 are auto generated from Beats modules and because of this sometimes get the newest structure faster.

We started to use the OS specific part in the configs but it is not supported yet, so best ignore it ;-)

Taking a step back: What is the problem you are trying to solve?

**Comment by 111andre111** [comment]
Well I started to work on your recommendation that you did here:
https://github.com/elastic/kibana/issues/64248
And I right just found out the described difference and wanted to understand what is the correct place to go forth.
But I think that answers my question.

The leading improvement place is not the beats part:
https://github.com/elastic/package-registry/tree/master/dev/packages/beats
but how I understand for upcoming improvements here:
https://github.com/elastic/package-registry/tree/master/dev/packages/example
and for longer running investigation modules will be here:
https://github.com/elastic/package-registry/tree/master/dev/packages/alpha
correct?

If not, please correct my understanding.

**Comment by ruflin** [comment]
In the end, all packages will be moved out of this repository. We first will move the `beats` ones: https://github.com/elastic/package-registry/issues/414 The best place to contribute at the moment is definitively the `alpha` ones as these are the ones that will be releases.

And yes, we should probably have a better description ;-)

**Comment by ruflin** [comment]
Closing as by now most packages except the ones needed for testing were moved to https://github.com/elastic/package-storage We still need to follow up with better docs.
