### ISSUE TITLE
Issues with some example package values

### ISSUE THREAD

**Issue by jfsiii** [elastic/package-registry#42]
## JSON vs JS objects
Any `searchSourceJSON `, `optionsJSON`, `panelsJSON`, `uiStateJSON`, and `visState` fields in [`dev/package-template`](https://github.com/elastic/integrations-registry/tree/master/dev/package-template) should be JSON strings, not JS objects.

I attempted to `bulkCreate` them and  got a `JSON.parse` error about `[object Object]`. The error started in a kibana migration handler and I worked backwards the issues in these keys. 

I don’t know if there are docs/schemas about this but the [`sample_data/data_sets`](https://github.com/elastic/kibana/blob/master/src/legacy/server/sample_data/data_sets/) have [examples](https://github.com/elastic/kibana/blob/e08f92b0f02325addc191e4b0057bd5efd4aa479/src/legacy/server/sample_data/data_sets/logs/saved_objects.js#L32-L43)

## Invalid JSON
The [example ingest pipeline](https://github.com/elastic/integrations-registry/blob/master/dev/package-template/elasticsearch/ingest-pipeline/default.json) has invalid JSON [at line 14](https://github.com/elastic/integrations-registry/blob/master/dev/package-template/elasticsearch/ingest-pipeline/default.json#L14)
<img width="570" alt="Screen Shot 2019-07-11 at 12 47 50 PM" src="https://user-images.githubusercontent.com/57655/61069370-2a562f00-a3da-11e9-939e-adc139ee83f5.png">

**Comment by ruflin** [comment]
This is actually a mistake made on my end I think. In Beats (from where I copied the data) we decode the JSON object for easier versioning (nice diffs). So the objects above have to be JSON encoded to work.

There are script in the Beats project that do this automatically but we need to change this data to be compatible and decide later on how we better version it (especially as this are only examples).

**Comment by jfsiii** [comment]
The Integrations Manager converts them to JSON in https://github.com/elastic/kibana/blob/feature-integrations-manager/x-pack/legacy/plugins/integrations_manager/server/integrations/get_objects.ts#L54 if you want to see all the keys to update

**Comment by ruflin** [comment]
@exekias We should discuss the format we want to have it in the package in the end for the Saved object json parts. If we let it encoded, it will be easier for contributors to just copy / paste their asset from Kibana. The downsides are that during development, diffs are impossible to read and is the reason we have it decoded in the modules repo so far.

**Comment by ruflin** [comment]
Closing as #157 was merged.
