### ISSUE TITLE
Associate dashboards with dataset

### ISSUE THREAD

**Issue by skh** [elastic/package-registry#424]
Currently, it is not possible to know what data is displayed on a dashboard. This means that for every data stream on the data streams list page, we link to all dashboards of the corresponding package. This list can be long, and not all dashboards will be relevant to the specific data stream.

This feature request is to define which dashboards are relevant for a given dataset, and specify that somewhere in the package (the `manifest.yml` of the dataset?) so that the UI can react accordingly.

**Comment by ruflin** [comment]
An alternative approach could be that we move visualizations which belong to a specific dataset under the dataset template. Then we know which dashboard uses which dataset (which creates a data stream) and from that know which dashboards to link to? If a visualization is on the package level we just assume it applies to all datasets.

**Comment by skh** [comment]
@ruflin That sounds good too.

If we ever want to link to visualizations directly from a data stream (or a similar dataset-specific place), the same problem would arise for visualization. However, I believe they are shared between dashboards so that sounds like a more complicated problem and I don't think we need to solve it.

**Comment by mtojek** [comment]
Keep in mind that there are also "overview" dashboards that collect data from multiple datasets.

**Comment by ruflin** [comment]
@ph I think we don't need this for beta1?

**Comment by skh** [comment]
> I think we don't need this for beta1?

Please reschedule as you see fit. I don't remember why I added that tag.

**Comment by ph** [comment]
Agree removed the label

**Comment by mtojek** [comment]
I don't reckon that any team requested this feature so far, so let me resolve it now as there isn't any progress here.

**Comment by ruflin** [comment]
@jen-huang Having the visualiszations / dashboards per dataset could potentially simplify the query that is used to link to dashboards in the data stream UI in Fleet.
