### ISSUE TITLE
go get: malformed file path

### ISSUE THREAD

**Issue by mtojek** [elastic/package-registry#430]
Once I tried to add a dependency between https://github.com/elastic/integrations and https://github.com/elastic/package-registry:

```bash
➜  integrations git:(move-import-beats-script) go get github.com/elastic/package-registry@master
go: downloading github.com/elastic/package-registry v0.2.1-0.20200505072038-497a6debc2f3
go get github.com/elastic/package-registry@master: create zip: malformed file path "testdata/package/example/0.0.2/kibana/index-pattern/filebeat-*.json": invalid char '*'
```

Not sure what to do with this one. Is it required to be there?

**Comment by ruflin** [comment]
Lol, nice error. Lets just rename `filebeat-*.json` to `filebeat.json`. That should do the trick?
