### ISSUE TITLE
Error trying to add a datasource to auditd package

### ISSUE THREAD

**Issue by neptunian** [elastic/package-registry#439]
<img width="1360" alt="Screen Shot 2020-04-30 at 6 26 34 PM" src="https://user-images.githubusercontent.com/1676003/80767174-4ff12800-8b15-11ea-8c37-ae153c640b09.png">

@jen-huang suspects it is either a problem in the UI parsing or incorrectly formatted template on the package registry side
https://epr.elastic.co/package/auditd/0.0.2

**Comment by jen-huang** [comment]
Transferred this to package-registry repo as the issue was that the auditd stream template was invalid Handlebars syntax. Is there is any way we can enforce valid handlebars on the registry side?

**Comment by ruflin** [comment]
@jen-huang Yes, we should validate handlebars on the registry side. Could you update the issue or create a new one?

BTW by now I removed the invalid auditd package.

**Comment by jen-huang** [comment]
Created #444 (nice number) for handlebars validation.
