### ISSUE TITLE
Discuss syntax to ingest pipeline references

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#441]
Today when a dataset contains multiple ingest pipelines, we support the following syntax to link to an other ingest pipeline:

```
'{{ IngestPipeline "pipeline-plaintext" }}'
```

Here `pipeline-plaintext` is the name (without the suffix) of the pipeline that is referenced. On the Kibana side we used a regexp to replace it with the correct name.

This issue is to discuss if we should keep this syntax or potentially changing it.

In some other parts of the packages we use [handlebars](https://handlebarsjs.com/guide/) for templates. In general I think we should only have one template language to make it easier for contributors to only learn 1 template language.

Relying on a common template language instead of custom code will also help us to for example validate packages on the registry side.

Looking at handlebars, customer helpers could be a solution here: https://handlebarsjs.com/guide/#custom-helpers Or is there a built-in helper we could already use?

**Comment by ruflin** [comment]
@jfsiii @skh Would be great to get your input on what you think would be best for the above from a Kibana perspective
@mtojek Would be great to get your input on what you think would be possible to deal with on the Golang side as you already played around with some templating for the readmes.

Any suggestions for the final syntax would be great.

**Comment by skh** [comment]
> Relying on a common template language instead of custom code will also help us to for example validate packages on the registry side.

I agree, if the task is complex enough that using a template library simplifies things. Most tasks are.

In this case, we're talking about replacing a one-line regular expression, which is documented and I hope fairly readable: https://github.com/elastic/kibana/blob/master/x-pack/plugins/ingest_manager/server/services/epm/elasticsearch/ingest_pipeline/install.ts#L56-L57

I don't think this use case on its own warrants the use of a template library, but we can certainly move this piece of code to handlebars in order to stay aligned with the rest of the codebase.

**Comment by mtojek** [comment]
I'm not a fan of the handlebars template engine. I understand it's lightweight, but also missing popular syntax forms: `if a == b`, method calls, inclusion.

To be clear, are we considering changing the templating engine to something else? of course, supported by both ends.

**Comment by ruflin** [comment]
@skh We must separate two things here: Syntax and what we use to process it. The reason we should use a known syntax like handlebars is that we can verify the syntax is valid and potentially have others to also process it. If we want to keep using regexp on the Kibana side I don't think it is a problem.

@mtojek Not attached to any template language as long as it is available cross platform. In the end what we do on the template side is pretty basic I think so I would assume most template engines should support it. Any preferences? Also something specific you couldn't do with handlebars so far that we need?

**Comment by mtojek** [comment]
> Also something specific you couldn't do with handlebars so far that we need?

Yes, as I said before: `if a == b`, method calls, template inclusion.

**Comment by ruflin** [comment]
@mtojek Could you link where you need these?

**Comment by mtojek** [comment]
It's rather a question for template completeness in terms of long-running migrations. 

Take a look at o365 filebeat input:

```yaml
{{ if eq "string" (printf "%T" .content_type) }}
```

```yaml
{{ if eq .input "o365audit" }}
```

In azure:

```yaml
          "pipeline": {
              "name": "{< IngestPipeline "azure-shared-pipeline" >}"
          }
```

**Comment by skh** [comment]
Please also note that ingest pipelines may contain field value placeholders delimited by `{{...}}`, see the examples in https://www.elastic.co/guide/en/elasticsearch/reference/current/accessing-data-in-pipelines.html.

So in ingest pipelines, we need a way to distinguish between placeholders replaced during package installation, and valid placeholder to be used by elasticsearch during ingestion.

I don't know which kind of placeholders `{{ if eq "string" (printf "%T" .content_type) }}` and `{{ if eq .input "o365audit" }}` are.

**Comment by ruflin** [comment]
From my perspective the o365 config is probably too complex: https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/o365/audit/config/input.yml The if input will not be needed as it is 2 files. For the content_type I wonder how this works. Is it something the user configures? Why is this `printf` needed here? @adriansr might be able to comment? I would rather simplify the configs as this will also help the users instead of having more complex templates.

**Comment by adriansr** [comment]
Mmm, probably right about o365 config being too complicated.

```
{{ if eq "string" (printf "%T" .content_type) }}
content_type: {{ .content_type }}
{{ else }}
content_type:
{{ range .content_type }}
 - {{ . }}
{{ end }}
```

What this does is, if `content_type` is of type string, it sets content type to this value.

Otherwise, it is an array (of strings), it makes a yaml list out of this.

Content-type is something intrinsic to the o365 audit API:

> The list of content-types to subscribe to. By default, it subscribes to all known content-types:
>      Audit.AzureActiveDirectory
>       Audit.Exchange
>       Audit.SharePoint
>       Audit.General
>       DLP.All

And yes we have to expect users deviating from the default as different content-types require different permissions to monitor.

I just made it support a string instead of a list because I expected users to be frustrated when they got an error for:

```yaml
content_type: DLP.All
```

instead of:

```yaml
content_type:
 - DLP.All
```

Maybe a bit of overthinking in there.

I don't know what your limitations are when migrating this to packages. Are breaking changes in config expected? This is module is shipping in 7.7.

**Comment by ruflin** [comment]
I was thinking even if content_type is an array and you pass `content_type: DLP.All`, go-ucfg would do the right thing? @urso can you comment?

I think if in the package we get rid of the string check, it can be fully migrated. But @mtojek will know more.

**Comment by ruflin** [comment]
We are nearing 7.9 and should not break the syntax anymore afterwards. @ph @ycombinator Would be great to get your input on this as you will look at it with fresh eyes.

@adriansr Are you still blocked by the above?

**Comment by adriansr** [comment]
@ruflin I don't know what you mean. I am not porting the o365 to packages so I am not blocked by anything.

I think it's currently possible to adapt the o365 config to packages without much trouble. It just looks more complicated than it really is.

**Comment by ruflin** [comment]
@adriansr Ok, glad to hear you are not blocked. Also good to know there is a workaround if it sounds like it is not optimal. Lets discuss this further when we port packages where it is "ugly".

**Comment by ruflin** [comment]
@ycombinator @mtojek With 7.10, we have again to make a change here. It ties a bit into the discussion around path vs src. What we have today works, so no need to change it.

My current suggestion is to take what we have and know it is not perfect but only improve it if we have something that actually does not work anymore and then deal with it with spec versions.

**Comment by ruflin** [comment]
Closing this as 7.10 FF is over and we can't change it anymore, at least not breaking it.
