### ISSUE TITLE
Discuss: How to ship default and required packages

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#446]
Some of the packages like `base`, `system` and `endpoint` are required by the Ingest Manager to work properly. This can cause some problems if the registry is run based on a user provided package directory as this might not contain the base packages. This case for example can happen during testing.

Few questions to discuss:

* How do we allow someone running his own registry to pull in the required / base packages?
* How do we notify users that they have to?

**Comment by mtojek** [comment]
How do we allow someone running his own registry to pull in the required / base packages?

> as workaround we can bundle latest revisions of internal packages (base, system, endpoint) 

together with EPR and serve them no matter what the custom package directory is

> How do we notify users that they have to?

How about this: Kibana checks the completeness of EPR and notify the user about potential issues. 

Here are some of my observations:

1. Package dependency: do some packages depend on other ones?
2. For users not installing packages: EPR unavailability will break the product for them too
3. Did we consider a setup where there is no access to the internet? I know the company can run their own registry, but I wonder if it's not feasible to have a bundle release (Kibana + EPR).

**Comment by ruflin** [comment]
* Bundling it with the registry: Would we make it part of the binary?
* Kibana checks: I think this is a must. If one of the packages is missing, we must show a good error. Do we already have a KB issue for that?
* Package dependencies: No, this was left out on purpose to keep things simple.
* EPR unavailability: Yes, but this is the same with maps.elastic.co today.
* On prem: Bundling Kibana with other things sounds like ECE

One thing we could also do, is instead of bundling the registry with the required packages that we bundle Kibana with the required packages. If Kibana starts up, it checks if a newer version is available in the registry, if not, it install the local version. The packages that would be bundled with Kibana would be the version that is available during build time or a specified one.

**Comment by ph** [comment]
> Kibana with the required packages. If Kibana starts up, it checks if a newer version is available in the registry, if not, it install the local version. The packages that would be bundled with Kibana would be the version that is available during build time or a specified one.

This introduces cross-project build dependencies, which I think might complicate stuff.

@ruflin Do we have a plan to distribute the registry outside of docker? If we don't we could have two flavor of the images:

* package-registry with all the packages
* package-registry-light: Default packages

**Comment by ruflin** [comment]
@ph As long as we don't make the registry to be run on prem, we only need the binary for testing or CI. If we make it available outside, the binary itself will always contain no packages, it is only in the docker case that we can "mix" the two together.

**Comment by ruflin** [comment]
By now, we don't require the base package anymore as it is included in Elasticsearch. We still have endpoint and system. These could potentially also be shipped / packaged with Kibana as .tar.gz and installed. The way this would work is that Kibana would then check, if the registry has a newer version and would install this. So the .tar.gz would only be applied, if no version is available yet but from there on the registry comes into play. Same is the case for the base package.

@ph Will unassign me from this one.

**Comment by mtojek** [comment]
I guess that there are similar talks around apm + synthetics + system, so I can resolve this issue.
