### ISSUE TITLE
Move alpha packages to package-storage and integrations

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#447]
Currently some of the packages are still developed inside the package-registry. But development of the packages should happen in https://github.com/elastic/integrations or an other repo and then for each version, a PR against https://github.com/elastic/package-storage should be opened. To get to this point, a few things must happen:

* Move over all existing alpha packages to package-storage. I propose we use version 0.1.0 for these.
* Remove alpha packages from registry
* Update Docker images in registry and storage to use the new location for the build
  * Potentially update magefile in registry to allow to easily boot up a local env or should it be in storage or integrations?
* Update docs

**Comment by ruflin** [comment]
@jonathan-buttner I wonder where we should move the development of the endpoint package? I would assume `integrations` repo would work for now. Like this you can benefit from all the tooling there.

**Comment by mtojek** [comment]
Thanks for the issue.

> Move over all existing alpha packages to package-storage. I propose we use version 0.1.0 for these.

I assume we should wait with this one, once every package is done?

**Comment by ruflin** [comment]
I would move already the ones that are completed to make sure no further changes happen in the package-registry and wait for the ones that still haven an open PR

**Comment by mtojek** [comment]
The thing that concerns me is that there is no validation mechanism in the package-registry, so it might be hard to address/fix/reproduce bugs without copying it first to the `integrations`.

**Comment by ruflin** [comment]
Doesn't have the package-registry the same validation mechanisms at the moment that integrations has?

Independent from that: No objections from my end to move over open PR's, I just worried it might slow down the contributors.

**Comment by mtojek** [comment]
> Doesn't have the package-registry the same validation mechanisms at the moment that integrations has?

The tools like https://github.com/elastic/integrations/issues/14 will be available in integrations.

**Comment by ruflin** [comment]
@mtojek I think I miss something here. I expect that the existing open PR's with packages will be merged in the next days and all future development happens in integrations. Did you mean above that no validation is happeing in the package-storage?

**Comment by mtojek** [comment]
I see a situation in which developer needs to fix "redis" integration and debug the ingest pipeline. In "integrations" you have tools to do this. As the "package-storage" is a simple store, you have no tools, so it's easier for you to copy them to "integrations" first.

Of course we can make the integration-tools public and free to use everywhere, but not sure if we have too many storage places now.

**Comment by jonathan-buttner** [comment]
> @jonathan-buttner I wonder where we should move the development of the endpoint package? I would assume `integrations` repo would work for now. Like this you can benefit from all the tooling there.

@ruflin Yeah I think that's fine. When changes are made to the endpoint package would we just open a PR against `integrations`? Or are there other steps we would need to do as well?

**Comment by ruflin** [comment]
@jonathan-buttner There will be two parts. The `integrations` repo is where the development of the package happens and as soon as it is ready, a PR with a new version again https://github.com/elastic/package-storage would have to be opened. But we are still working on all this and hopefully can automate it mostly. I'll ping you as soon as things are ready.

**Comment by mtojek** [comment]
> @jonathan-buttner There will be two parts. The `integrations` repo is where the development of the package happens and as soon as it is ready, a PR with a new version again https://github.com/elastic/package-storage would have to be opened.

@ruflin Let's focus on the repository file structure.

1. Should we keep `alpha` and `beats` directories inside the `dev/packages/beats` or we should combine these two into single `dev/packages`?
2. Do we want to move `dev/packages` to the root level, simply `packages`?

**Comment by ruflin** [comment]
The main reason some packages will be in the package-registry is for development and testing. Good example here are the longdocs package etc. So these will be packages that are never shipped in production. `packages` on the top level sounds like the right place here without any sub directory.

All the other packages we want to pull in for convenience like from the storage should land under build like you already did.

There are currently 2 exceptions: `base` and `endpoint`. Where does the development of these packages happen at the moment? I'm ok to also keep it under `packages` for now and move them out when we found the right place. For release, I expect us to copy them over to `package-storage`.

**Comment by mtojek** [comment]
Migration has been finished. Let me close this issue.
