### ISSUE TITLE
Discuss: Should registry remove 'removable' property?

### ISSUE THREAD

**Issue by jfsiii** [elastic/package-registry#455]
The packages on the registry are shipped with a `removable` property which Kibana uses to determine if the package is required / can be removed.

This feels like a Kibana concern. Why should the registry or package owner have this control over Kibana?

This also makes validation very important so that a package, especially a malicious one, isn't marked as unremovable.

I would like to explore storing this in Kibana. Is there a good reason to do it in the registry?

**Comment by ruflin** [comment]
The advantage of having it in the package is that we can decide it `ad-hoc`. Meaning someone already using 7.8 and we ship now a package later where `removable: false`, we would not need to change Kibana. But it feels like a made up case which will not happen in reality. Why should a package when 7.8 shipped have been removable but not later on.

+1 on my end to store this in KB instead of the package. Also makes sure contributors don't mess around with this flag. But we will need a way down the road that other Kibana plugins can hook into this to specify also other packages, for example endpoint to not be removable.

Where did we land with the required packages? Is this specified in Kibana?

**Comment by ruflin** [comment]
@jfsiii @paul-tavares @jonathan-buttner  I would like to move forward on this and store it in Kibana instaed of the package. I assume changes in KB would need to happen first?

**Comment by jonathan-buttner** [comment]
> @jfsiii @paul-tavares @jonathan-buttner I would like to move forward on this and store it in Kibana instaed of the package. I assume changes in KB would need to happen first?

Moving it to Kibana sounds good to me. Yeah we'll probably want the changes to be in Kibana first. I don't think it matters for 7.8 for the endpoint package but would removing the `removable` field from the system package allow a user on 7.8 to remove the system package? Is that a concern?

**Comment by paul-tavares** [comment]
I agree that this should be done in Kibana. Our (Endpoint) concern was/is that the Endpoint package should be a) installed by default, and b) can NOT be uninstalled, so regardless of approach, if that can be provide we're good 😃

**Comment by ruflin** [comment]
@jonathan-buttner In 7.8 only the packages we have already built are available and also package-registry version will stay the same. I also assume we will not touch 7.8 code anymore, so this discussion only applies to 7.9.

@paul-tavares Could you take a lead on getting this into Kibana so we can remove it afterwards in the registry?

**Comment by jfsiii** [comment]
@paul-tavares Ingest can prevent users from using its API or UI to uninstall a package, but that's it. With the right queries/permissions a user could still remove the dashboards, etc from ES

**Comment by paul-tavares** [comment]
@jfsiii understood - a supperuser/root type of user can always cause havoc 😆  
It's not so much an issue with dashboards configurations, but more with having a user action impact the ability for an entire app to function (endpoint management) if for some reason we would allow them to just hit "delete" on the endpoint package. Our package sets up Elastic search indexes and schemas in support of the app. Allowing a user to do it would be equivilant to someone deleting the `base` and/or the `system` package - I think Ingest as a whole would break right?

@ruflin Sure, I can take a look, but might not be right away - but def. for 7.9 😄 

//cc @kevinlog

**Comment by kevinlog** [comment]
Sounds good @paul-tavares @ruflin 
We'll create a ticket and get it prioritized for 7.9

**Comment by ruflin** [comment]
I opened https://github.com/elastic/package-registry/pull/532 to get this into the registry but will not merge it before the change made it into Kibana.

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/package-registry/pull/532 was merged.
