### ISSUE TITLE
Move part of the package generator code into package-registry service

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#461]
Today there are 2 steps when someone wants to run the registry:

* Run `mage build`: This copies all the content to `public` and makes some transformation on the data and adds files
* `go run .`: Starts the service

The registry should be able to run on any data structure which is like the package-storage repository without needing any build commands before. This means some of the generator code should be moved into the registry code to do this generation on startup or it should be removed and made a requirement of the package.

The following files should be generated when the registry is started up (or served on demand):

* .tar.gz files
* index.json files

At the moment there is also some transition on the saved objects to move them from decoded to encoded. This should be moved out of the packages itself that the final package already contains encoded saved objects and no transition has to happen. I would still encourage that we store in `integrations` repo the dashboards decoded and have build code to encode it, but it should not be supported by the registry and package storage itself. The encoding code should be removed and packages in package-storage adjusted accordingly.

One of the things that is done today, is that all files are copied over to a public directory and modified there. How will the registry deal with this in the future to not add files to the original files? Will it for now also create a copy of the files in a separate directory on startup?

**Comment by ruflin** [comment]
@exekias @mtojek would be great to get your thoughts on this.

**Comment by exekias** [comment]
I'm not sure I fully understood the last bit. If the files are already encoded in the `package-storage`, what's the transformation that the registry needs to do?

**Comment by ruflin** [comment]
If the dashboards are already encoded, no transformation is needed. And for the "copy of files" this becomes obsoelete, as we create it on the fly. In short, the `mage build` part is becoming obsolete.

**Comment by ruflin** [comment]
Closing this as with https://github.com/elastic/package-registry/pull/525 the build step goes away.
