### ISSUE TITLE
Add integration test with Ingest Manager

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#462]
Any change in the package registry can effect the Ingest Manager in Kibana. Because of this normally when I do changes on the package registry I spin up Kibana, run the /setup step of the Ingest Manager and run an agent to ingest some basic data to see if any errors are triggered. It would be great to automate this and have it as part of the CI.

**Comment by ruflin** [comment]
The way I do this locally currently is:

```
cd testing/environments
docker-compose -f snapshot.yml -f local.yml up --force-recreate
# Wait until all containers are healthy
curl -X POST http://elastic:changeme@localhost:5601/api/ingest_manager/setup -H "kbn-xsrf: ingest_manager"
# Make sure not errors are returned
```

@mtojek WDYT about adding something like above as an additional test command?

**Comment by mtojek** [comment]
Hmm.. actually I was planning to remove the "testing/environment" from this repo and only use the one defined in integrations. We need tools for this too :)

As long as we don't have tools, we can either checkout testing/environment from "integrations" or continue working on the copy here.

**Comment by ruflin** [comment]
I think we need to have it in both places as they have a bit different purposes, even though the code at the moment will be identical. This one here is to test, if package-registry changes work with the ingest manager. The one in the integrations repo is to test the packages itself. 

I don't think we package-registry should have a dependency on the integrations repo.

**Comment by mtojek** [comment]
> I don't think we package-registry should have a dependency on the integrations repo.

Neither do I. In the future it can use the "tools".

Also, I believe the `docker-compose.yml` file in this repository needs an update.

**Comment by ruflin** [comment]
Closing as some basic integration tests with Kibana have been added. Future refactoring need.
