### ISSUE TITLE
Change usage of `categories`

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#478]
The current categories in the packages are `logs`, `metrics`. But instead these should be more like `database`, `cache` etc. 

The values for the dataset type which is `logs`, `metrics` and should not have to be set by the users as it should be possible to extract these from the datasets.

**Comment by ruflin** [comment]
With https://github.com/elastic/package-registry/issues/482 moving forward for me it also clarifies where we should be going here:

* For `dataset.type` we already have it today inside each dataset manifest: https://github.com/elastic/package-registry/blob/master/testdata/package/default-pipeline/0.0.2/dataset/foo/manifest.yml#L4 We must validate that these can only be `logs` or `metrics` for now.
* If needed for querying, these types could also be exposed as a summary of all datasets on the package level

For the categories, I'm starting to think the category should be defined per dataset and not on the package level. And what we present on the package level for categories, is a summary of the categories in each dataset. I assume in most cases. all dataset of a single package will have the same category but it is not a requirement. @mostlyjason WDYT?

Following the above, we would have `category: foo` in each dataset. The nice part about this is that it also makes sure each dataset has only one category. These should then be validated against the valid categories. 

@mostlyjason Is this list of categories valid?
```
Cloud
Config management
Containers
AWS
Azure
Cointainer
CRM
Custom
Datastore
Elastic Stack
Google Cloud
Kubernetes
Languages
Message Queue
Monitoring
Network
Notification
Orchestration
OS & System
Productivity
Security
Support
Ticketing
Version Control
Web
```

**Comment by mostlyjason** [comment]
Linking this issue so we can follow recommendations made there https://github.com/elastic/dev/issues/1429

**Comment by ruflin** [comment]
I opened https://github.com/elastic/package-registry/pull/534 with the change. For now only package categories are adjusted.

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/package-registry/pull/534 was merged and old categories were removed.
