### ISSUE TITLE
Proposal: Cleanup requirement section in config and packages

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#499]
Today the requirement block in quite a few of our packages looks as following:

```
requirement:
  elasticsearch:
    versions: ">7.4.0"
  kibana:
    versions: ">7.4.0"
```

Even though the registry currently reads out all of these requirements, the only one that can be queried in the search endpoint is `kibana.version` based on the `kibana` query param.

As we don't need the elasticsearch requirement (yet), I suggest we remove support for it. Also as Kibana and Elasticsearch are normally on the same minor, not both are required. @hbharding This might also have effects on the design.

For the Kibana requirement, we should clean up all the requirements to something like `>=7.9.0` as none of these packages is supported in anything older than 7.9. One problem with this that lets assume we are on 8.0 and the package was removed, this old package will still show up even though potentially newer packages with `<=8.0.0` were release. I guess in this case, we need to update these old packages unfortunately when we know they are not compatible anymore.

To make the query param in the registry more descriptive I suggest we change it to `kibana.version` instead of just `kibana`. 

# Naming alternative

As an alternative to having Kibana as a requirement, I was thinking we could also just use the stack as a requirement. So the config would become `requirement.stack.versions` instead of Kibana. This would be based on the assumption, that if we ship a new version of a package with a higher requirement for the stack, it applies to all parts. This simplifies things but it could pose a problem to the Agent which can lag behind.

# Overall Alternative

I was also thinking about an alternative to the above. Instead of having to define it in YAML, using something more like a query language to define the requirements / constraints, similar to https://github.com/elastic/beats/issues/19068 This means it would then look like:

```
constraints:
- validate_version( {{kibana.version}}, >=7.9.0 )
```

This would make the query part much more powerful but it means we can't really expose the requirements in our UI.

**Comment by ruflin** [comment]
@mtojek @fearful-symmetry @jonathan-buttner Would be great to get your input on the above.

**Comment by mtojek** [comment]
I don't see any dependency on this field. I think the value is hardcoded (import-beats).

**Comment by ruflin** [comment]
An old package should never be touched. But there are at least 2 problems here:

1) We keep improving the registry and add more validation. Sometimes through additional validation it turns out, an old package actually was not valid but we didn't spot it. Now that the registry validates all packages on startup, how do we deal with it?
2) We had set a requirement on an old package >= 7.9 but later it turns out, it is not compatible with 8.1. I think one way to solve this is that we never define something should be compatible with the next major and are more strict in the versions?

**Comment by ruflin** [comment]
Closing, we went with 

```
conditions:
  kibana.version: "^7.4"
```

as an example.
