### ISSUE TITLE
Allow for multiple paths in "publicDir"

### ISSUE THREAD

**Issue by mtojek** [elastic/package-registry#505]
The aim of this task is to modify the Package Registry to allow for multiple different paths, similarly to the system PATH environment variable.

Justification:
When mounting the `/registry/public` directory, we need to prepare the source point:
1. Fetch package-storage.
2. Add the interesting ones (e.g. an integration a developer is currently working on)
3. Build all packages.
4. Mount the directory.

It would be much simpler, if the developer needs to prepare an additional custom public directory with built only single integration. No need for visiting package-storage if the target Docker image for registry already contains mandatory packages.

The registry would update version conflicts, the latter one in `publicDir` overrides previous revisions.

**Comment by ruflin** [comment]
Assuming that we get completely rid of `mage build` and the registry can just read from directories directly, we could probably also get rid of the `public` name here as it is just `packagePaths`.

**Comment by mtojek** [comment]
I'm going with this one.
