### ISSUE TITLE
Write tests for package validation

### ISSUE THREAD

**Issue by mtojek** [elastic/package-registry#523]
Outcome of: https://github.com/elastic/package-registry/pull/521

It would be great to have some positive and negative tests of package validation, e.g. packages without required fields.

**Comment by ruflin** [comment]
@mtojek @ycombinator Should we move this to `elastic-package` or `package-spec` repo?

**Comment by mtojek** [comment]
We already have some negative and positive tests, so I guess we can resolve this one.
