### ISSUE TITLE
Remove `event` dataset.type support from registry

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#530]
Currently the registry supports `dataset.type: event` as the endpoint package still uses it. This should be removed as soon as the endpoint package is not using it anymore.

**Comment by ruflin** [comment]
@jonathan-buttner Not sure what the best path forward here is. Should we potentially remove the old packages that still use event?

**Comment by jonathan-buttner** [comment]
> @jonathan-buttner Not sure what the best path forward here is. Should we potentially remove the old packages that still use event?

Yeah it's probably easiest to just delete our old packages. I'll need probably a day or so to get everything ready for that. I need a couple PRs to go in:

https://github.com/elastic/kibana/pull/69589 once that's merged I can rebuild our package without the `events` dataset and do a release, then we can delete everything before that version

**Comment by ruflin** [comment]
++

**Comment by ruflin** [comment]
PR is open here: https://github.com/elastic/package-registry/pull/567

**Comment by ruflin** [comment]
Closing as PR was merged.
