### ISSUE TITLE
Delay support for os specific packages

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#533]
In the future, we plan to support OS specific configurations options like paths per os. An example can be found here: https://github.com/elastic/package-storage/blob/c3db4fa7148841ace67639a82a27d62ab257b1f8/packages/mysql/0.1.0/dataset/error/manifest.yml#L16

We don't support it today and it will not be supported in 7.9. Even though we already came up with a suggested format on how it should look like, I suggest we remove it from all existing packages for now so moving forward we keep the flexibility to implement it the way it is best, meaning it will be an addition only and prevent any breaking change.

Also on the registry side we don't validate it at the moment but as soon as we support it, we should.

**Comment by ruflin** [comment]
@jen-huang FYI
@mtojek I think this has mostly an effect on the package generator?

**Comment by mtojek** [comment]
I think it supported it at some point, but wouldn't focus much on it, as there is no decision yet what to do with the generator. You can open an issue for integrations if it becomes an issue.

**Comment by jen-huang** [comment]
Noted. Removal won't affect Kibana side.

**Comment by ruflin** [comment]
@mtojek I filed https://github.com/elastic/integrations/issues/108

**Comment by ruflin** [comment]
Here is a follow up issue to rethink it in the future: https://github.com/elastic/package-registry/issues/548

**Comment by ruflin** [comment]
Closing as all related changes were implemented.
