### ISSUE TITLE
Too many open files for many .tar.gz downloads

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#535]
For so load tests I run the following command:

```
wrk -c 200 -d 30 -t 20 http://localhost:8080/epr/cisco/cisco-0.1.2.tar.gz
```

Unfortunately quite a few errors were returned. Digging into it I found the following errors in the registry logs:

```
2020/06/22 15:20:36 archiving package path 'public/package/cisco/0.1.2' failed: 1 error: processing package path 'public/package/cisco/0.1.2' failed: fcntl: too many open files
```

The problem is that we build the `.tar.gz` currently on the fly and rebuild it every time a request comes in. Few potential solutions:

* Limit the number of parallel requests
* Cache file paths for a certain time
* Cache .tar.gz for a certrain time

Caching the full .tar.gz is probably the most effective approach as it eliminates all file accesses.

**Comment by ruflin** [comment]
@mtojek WDYT would be the best approach to solve the above?

**Comment by mtojek** [comment]
First of all, please post any reports from the load test, so we can review them.

A couple of questions:
1. How did you run the registry?
2. Was it on Linux/Mac/under Docker?
3. What is the system limit for open files (hence the error). Keep in mind that if you fire a load test from the same host as the target, you will use more descriptors (client, server).

I would leave caching to be the last possible solution and focus on optimizing process of building the package (visiting resources might be faster). Remember, there is CDN in between.

**Comment by ruflin** [comment]
* The registry is run locally on OS X
* kern.maxfilesperproc: 24576

Even though there is a CDN in between, it is way too easy to reach this limit. Caching / prebuilding is in our case is simple as these assets for now don't change over time.

**Comment by mtojek** [comment]
You can also verify if descriptors not leaking anywhere.

**Comment by mtojek** [comment]
@jsoriano This issue might be relevant for https://github.com/elastic/package-registry/pull/703

**Comment by mtojek** [comment]
No error occurrences recently, so let me resolve this one.
