### ISSUE TITLE
Rename index-template directory to index_template

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#565]
As discussed in https://github.com/elastic/package-registry/pull/552#discussion_r445622417 for consistency reason we should use `-` or `_` for all the directory names. The only exception at the moment is `index-template`. Instead it should be called `index_template`.

To support this change, not changes in the package-registry are needed but Kibana and packages need to be updated. The suggested path forward is:

* [ ] Update all packages with `index_template` but also keep `index-template` as a duplicate around https://github.com/elastic/package-storage/pull/90
* [ ] Switch Kibana over to `index_template`, `ilm_policy`, `component_template`
* [ ] Remove all `index-template` directory in packages.

**Comment by ruflin** [comment]
Updating the base package, I realised there is also `component-template` and `ilm-policy`. I renamed both to `component_template` and `ilm_policy`. These also need to be updated on the Kibana side.

**Comment by ruflin** [comment]
@ycombinator @jonathan-buttner @mtojek Do you know of a place other then the base package where we use the above paths? Or one more path using `-`?

**Comment by jonathan-buttner** [comment]
> @ycombinator @jonathan-buttner @mtojek Do you know of a place other then the base package where we use the above paths? Or one more path using `-`?

Thanks for the ping. I'm not aware of any others 👍

**Comment by ycombinator** [comment]
@ruflin What about the `ingest-pipeline` directories?

```
development/github/package-storage ‹master› » find packages -iname *-* -type d | awk -F\/ '{print $NF}' | sort | uniq -c
   3 component-template
   3 ilm-policy
   3 index-template
  65 ingest-pipeline
```

**Comment by ruflin** [comment]
@ycombinator Looks like I'm missed these :-(

**Comment by ruflin** [comment]
This now becomes a bit more complicated because of the ingest-pipelines as these exist in all packages. My thinking: Also add duplicates for the ingest-pipeline directory in all packages, get https://github.com/elastic/kibana/pull/70320 in and then remove it?

**Comment by ruflin** [comment]
We now copied all directories with `-` in package-registry, package-storage and integrations repo to make it compatible with https://github.com/elastic/kibana/pull/70320. The old directories can be removed when snapshot builds with https://github.com/elastic/kibana/pull/70320 are available which is probably in the next 24h.

**Comment by ruflin** [comment]
Kibana updated, all assets removed from package-storage and package-registry and check built into registry now. Closing this issue.
