### ISSUE TITLE
Content type text/plain sent for json files

### ISSUE THREAD

**Issue by skh** [elastic/package-registry#590]
https://epr.elastic.co/package/aws/0.1.1/kibana/visualization/1235fe50-41e7-11e9-b7a0-c99d9d127b61.json

replies with 

`content-type: text/plain; charset=utf-8`

It used to be `application/json`.

This is probably not an intentional change.

**Comment by skh** [comment]
From a slack discussion, this might be related to changing the base image of the container from ubuntu to centos (unconfirmed).

**Comment by mtojek** [comment]
I'm looking at this one.

**Comment by mtojek** [comment]
I found the issue and indeed it was due to changing the operating system. The PR is ready, but most likely it will take some time until it reaches all environments (snapshot, staging, production).
