### ISSUE TITLE
Validate existence of TemplatePath for all streams

### ISSUE THREAD

**Issue by jen-huang** [elastic/package-registry#595]
We should validate that all package streams have a `TemplatePath`, otherwise Kibana gives an error when trying to add a stream that doesn't have one. Details: https://github.com/elastic/integrations/issues/175

**Comment by ph** [comment]
@ruflin  Does it need to be defined at the stream level, could we define one and  reuse?

**Comment by mtojek** [comment]
The implementation of the package-registry enforces the presence of the `template_path` (see: https://github.com/elastic/package-registry/blob/master/util/dataset.go#L141). If it behaves differently, the bug is on the package-registry side, not integrations.

**Comment by ruflin** [comment]
This was a bug in the registry: https://github.com/elastic/package-registry/pull/600 All the disabled by default streams did not have it populated :-(
