### ISSUE TITLE
Add support for testing the registry against multiple stack version

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#615]
Currently the package-registry is tested again 7.9.0-SNAPSHOT as this is the first version in production that works against it. Moving forward, the registry must be compatible with many versions of the Elastic Stack and we should ensure with CI, that this is the case. 

The first versions we should add is `8.0.0-SNAPSHOT` master to detect any potential breaking changes and `7.10.0-SNAPSHOT`. 

On the implementation side a few ideas:

* Use environment variables in the [compose files](https://github.com/elastic/package-registry/blob/master/testing/environments/snapshot.yml#L6), something like `docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION:-7.9.0}-SNAPSHOT`. Then pass this in to [main_integration_test](https://github.com/elastic/package-registry/blob/master/main_integration_test.go) during testing to setup a specific environment. This works as long as the config params for the setup stay the same for all versions.
* Alternative, use multiple compose files for the different versions and select them based on a param.
* On CI, run them as parallel jobs to no increase build time
* At one stage we will hit the limit of "reasonable" builds for each PR, then we could switch to check all the versions "daily" or similar.

**Comment by ruflin** [comment]
@mtojek @ycombinator I think the above not only applies to package-registry, but also to package-storage and integrations. So if we figure out a solution in any of these places, we can reuse it probably.

**Comment by ycombinator** [comment]
I like the first suggestion of using environment variables. I would couple that with a `supported-versions.yml` file like we do in Beats in some places, e.g.https://github.com/elastic/beats/blob/master/metricbeat/module/kafka/_meta/supported-versions.yml. 

> At one stage we will hit the limit of "reasonable" builds for each PR, then we could switch to check all the versions "daily" or similar.
This would definitely work but that daily CI job might also take quite long. An alternate scaling strategy might be to choose a random N supported versions from `supported-versions.yml` in any single CI job run.

**Comment by ruflin** [comment]
We are currently testing the registry against 7.10.0-SNAPSHOT: https://github.com/elastic/package-registry/blob/master/testing/environments/snapshot.yml#L6 Until we have something like this implemented, what is the version we should test against? Is the oldest supported Kibana version the right one as the assumption is made there are no breaking changes in the same minors? So should we stick to 7.10.0?

**Comment by ycombinator** [comment]
Yes, until this issue is resolved, I agree that testing with `7.10.0` of Kibana is the safest way to go to ensure that new changes to the package registry keep working with older Kibana versions.

**Comment by ruflin** [comment]
Ok. We should probably move to 7.10.0 non snapshot because I remember at one stage, the `-SNAPSHOT` ones are cleaned up.

**Comment by ycombinator** [comment]
> Ok. We should probably move to 7.10.0 non snapshot because I remember at one stage, the -SNAPSHOT ones are cleaned up.

++ let me quickly put up a PR for this.

**Comment by mtojek** [comment]
We are already testing against different stack versions.
