### ISSUE TITLE
Allow package registry to display a message in Kibana

### ISSUE THREAD

**Issue by ph** [elastic/package-registry#627]
It would be great if we could define a message in the registry that will be shown in the ingest manager, the use case for it would be to warn on important changes.

- We are about to change the registry and remove it.
- We want to ask them to upgrade their setup. (beta to final)
- There was an outage that we want to warn them / apologize.

I see this as a separate call that will display a banner in Kibana.

@ruflin

**Comment by alvarolobato** [comment]
++ I was talking about this today with @ruflin we have that need for 7.8 and it would be convenient for other similar situations.

**Comment by ruflin** [comment]
One idea here would be to introduce a separate `status` subdomain, for example `https://status.epr.elastic.co/`. This would allow us to also have different status pages for different registries.

If `/` on the registry side returns a `404`, `500` or service cannot be found, Kibana should reach out to `status.*` and show this message instead. As I expect this to be only consumed by machines, we could also put there JSON with more information when needed but start with `{"message": "Foo bar"}´. 

On the hosting side `status.*` I would expect it to point to a static S3 bucket (or similar) with a static file.

**Comment by ph** [comment]
@alvarolobato Yes, When you suggested this I was thinking about how we were doing it in my previous job. We used it to:

- Tell users when we screwed up. :)
- Tell users when we were doing a special outage.
- Tell users to try out something new.

 To be honest, I see values even outside of the EPR domain.  But let's keep it simple for now.

@ruflin There are multiples way we can do that:

1. it could be even a "message" node in any response of the API.
2. We could make system do a call on /messages everything not just on 500.
3. Like you proposed call on errors.


I think maybe a combination of 2 and 3 is a better way because we could use it for other things than just errors. IE: We are looking for special feedback fo X feature follow the link.

I am sure that @mostlyjason could also find other use case. :)

**Comment by ruflin** [comment]
I think the error message / status should come from a different domain. This allows us more flexibility on how to deploy it. Did I mention that the registry service actually has a `health` endpoint? https://epr.elastic.co/health

**Comment by ph** [comment]
I supposed https://epr.elastic.co/health required the right json header? Is the flexibility reason is having it server from an S3 bucket? How will you deal with versions?

**Comment by ruflin** [comment]
* What you mean by the right json header?
* Having status.* running in a different location be it S3 or other sounds like a good idea as otherwise when the service is down, also the status page is down.

**Comment by ph** [comment]
doing `curl https://epr.elastic.co/health` doesn't return any content? You are just returning a 200?

**Comment by ruflin** [comment]
Yes, we can do more if needed. Currently this is for Docker / k8s health check.

**Comment by mostlyjason** [comment]
Could we add it here https://status.elastic.co/?

**Comment by ruflin** [comment]
@mostlyjason I think the status itself for the registry could also be added to this page. But I don't think it is the place where we would consume a message from to be shown in Kibana.

**Comment by ruflin** [comment]
I think we are trying to solve 2 different problem in one go with the above and we need to separate. One is about outages / migration and the other one is about permanent changes / removal of a registry. Let me propose a path forward for both.

# Temporary outages / status

For various reasons, it is possible that the registry is not available. Be it local network failure, maintenance on our end, upgrades with down time. This is a temporary outage. Our goal is always that this does not happen but 100% availability does not exist.

First, the status of the registry should show up under "status.elastic.co". This data is coming from automated monitoring and in case of an incident, we can show messages on this page (still need to figure out how). What we need to make sure is that our users are aware of this page and can navigate there in case of an outage.

For this, we need to improve our messaging in Kibana in case the registry is not available:

![image](https://user-images.githubusercontent.com/244900/93591511-d6b57d00-f9b0-11ea-89ce-367e19022337.png)

There is more than one message based on the error. But we should add additional information for the user on what action to take.

There might be other reasons why the registry is not available, be it a proxy, firewall or local network issues. Also the case where the registry is hosted on prem (https://github.com/elastic/kibana/issues/77333) could offer different problems but we should tackled this separately.

Next step here is to create an issue in Kibana with a much better error message and more details.

# Permanent changes

Permanent changes are things like the removal of a registry or remove compatibility of a certain version from the registry. The reason can be what we have right now, it is an experimental release or in a few years, that certain version of the stack are EOL. In the best case, this never happens but reality always looks different.

The challenge around the above cases is that normally it is only after that the need for such a message comes up and it might be different for each Kibana version.

What if we would create a single static page that contains all the compatibility information about the registry. This is also the place, where we could embed special messaging. So in case of an error, we send the user to `status.elastic.co` but also provide a second link where the user can go to, to get more info about the error.

Going the above route simplifies things to not trying a technical solution that covers all edge cases but instead link users to a curated page where the info is available.

We can't solve the 7.8 problem with the above and in 7.9, we can also solve it for the next bugfix releases. So for 7.8, we will need to link users manually on discuss to the page we created to inform them.

**Comment by ruflin** [comment]
@ph I will unassigne myself from this one but I think it is still something we should add to our roadmap.

**Comment by mtojek** [comment]
Closing this issue as we haven't heard any calls for the status page. Feel free to reopen if you have a use case.
