### ISSUE TITLE
[Ingest Manager] Run the e2e-testing Fleet Kibana / Agent tests during CI for Registry changes

### ISSUE THREAD

**Issue by EricDavisX** [elastic/package-registry#630]
**Describe the enhancement:**
Enhance package-registry CI to call a new e2e Agent & Kibana Fleet test during CI

 - the Observability Automation Team was kind enough to help us set up a small initial test for Elastic Agent and Kibana Ingest Manager / Fleet!  The next step is to have it run in all of the projects CI that go into making it all work, including Registry.

The e2e test is here:
https://github.com/elastic/e2e-testing/tree/master/e2e/_suites/ingest-manager

It can be called as, from the elastic/e2e-testing repo e2e/_suites/ingest-manager
$ godog -t stand_alone_mode
 - it would also need dependencies of course.  specifics are being Doc'ed for that immediately so we can use them here.

**Describe a specific use case for the enhancement or feature:**
Lets say a developer somehow includes a bug in the pr for the code they're changing, CI could catch it so it isn't merged, which saves the company time overall.

@mdelapenya thanks for helping guide this.

this will be fixed before we look to implement this, but calling out the nuance in case it relates still - https://github.com/elastic/e2e-testing/issues/253
 - the test is built with docker containers, so as part of the test we'd need to be sure to build the Registry container from current pr code and use it as part of the test against a specific distribution, like the 'snapshots' line.

**Comment by ruflin** [comment]
@mdelapenya I assume this will only need changes on the Jenkinsfiles? Will you take care of these changes?

**Comment by EricDavisX** [comment]
The work is all but done, Kibana PRs can now use a bot message to run the e2e-tests here and use a newly created Kibana image in the test!  

We have only a little bit of work left to make it fully automated based on specific desired files in the Kibana repo (which files should those be is one question).

**Comment by EricDavisX** [comment]
I raised this to the Fleet team and we'll talk about priority and need and review against how much is covered in Unit tests for Registry.

**Comment by mtojek** [comment]
Package Registry is mainly guarded with contract tests implemented using Go unit tests:

https://github.com/elastic/package-registry/blob/master/main_test.go#L47-L67
https://github.com/elastic/package-registry/tree/master/testdata/generated

which means that all critical paths (positive and negative) are covered. These tests execute in seconds. There is also an additional "fleet setup" test: https://github.com/elastic/package-registry/blob/master/main_integration_test.go#L82

I'm not sure if we want to introduce e2e-tests which may introduce additional flakiness and, I guess, some tests will be redundant with ones running in other repos.

Is there anything missed here that e2e-tests can introduce? If so, let's see if that can be implemented as contract tests.

**Comment by ruflin** [comment]
I think there is some potential value in having e2e tests for covering tests against different versions of Kibana, this would not be on PR but after merges. At the same time, this should already happen as soon as the recent changes go into `distribution:snapshot`. It means, potential issues with older versions of Kibana would only be discovered at this stage.

**Comment by mtojek** [comment]
> I think there is some potential value in having e2e tests for covering tests against different versions of Kibana, this would not be on PR but after merges.

FYI We configured the CI for elastic/integrations to try to install packages in the last 3 stack versions. We run all tests only in the latest stack not to elongate build runs.
