### ISSUE TITLE
Return package sorted by pacakge title

### ISSUE THREAD

**Issue by ph** [elastic/package-registry#647]
Originally created by @mostlyjason  on https://github.com/elastic/kibana/issues/74577
---

Currently, the list of integrations shown in Ingest Manager is not alphabetically sorted. This makes it more difficult to find integrations as the number grows from 39 and higher. You can see in the screenshot below that Big IP comes after the letter C. Also custom logs, is after the letter 'K'. It seems like there some kind of sort, but its not sorted based on the name displayed on the screen.

![image](https://user-images.githubusercontent.com/6370704/89566782-8a81f500-d7d5-11ea-8711-81695a4e5784.png)

**Comment by ph** [comment]
@mtojek @ycombinator

**Comment by ruflin** [comment]
Currently the packages are sorted by the package name: https://github.com/elastic/package-registry/blob/master/search.go#L172 I think what you are looking for is to sort it by package title?

Example here of the Big IP Package:

```
  {
    "name": "f5",
    "title": "Big-IP Access Policy Manager",
    "version": "0.1.0",
    "release": "experimental",
    "description": "Big-IP Access Policy Manager Integration",
    "type": "integration",
    "download": "/epr/f5/f5-0.1.0.zip",
    "path": "/package/f5/0.1.0"
  },
```

**Comment by jlind23** [comment]
@mtojek is it something still relevant?

**Comment by mtojek** [comment]
I suggest to review titles and package names first. In the example you brought: 

Package name: f5
Package title: Big-IP Access Policy Manager

Shouldn't it be consistent to have "F5 Big-IP..."? If you're used to package names (e.g. f5), you will look for it at the right place in the alphabet. I understand that it might be misleading if you are browsing packages ordered by titles. Anyway it shouldn't be a complex adjustment in the source code (let me see if I can prepare a quick fix).

**Comment by jlind23** [comment]
I do agree that name and titles should be consistent!

Sorting by title is not a viable option I think. What if I am looking for F5? Should I scroll down until "Big-IP ..."? That's weird also. What do you think?

**Comment by mtojek** [comment]
In this particular case (F5) I agree with you, but I'm not convinced in the other case: log vs "Custom logs". That's the reason why we may need to adjust ordering.
