### ISSUE TITLE
Implement package pipelines

### ISSUE THREAD

**Issue by jalvz** [elastic/package-registry#659]
The package [registry](https://github.com/elastic/package-registry#package-structure) accounts for the possibility of package-level pipelines, that is, not tied to an specific data stream ([example](https://github.com/elastic/package-registry/tree/master/testdata/package/example/0.0.2)).

This is very convenient for APM because most of our pipelines are applicable to all event (data stream) types.
While the spec validates the structure, it seems that Kibana ignores package pipelines completely.

This feature request it to implement the Kibana side.

**Comment by mtojek** [comment]
AFAIR Package pipelines are supported now, so resolving.
