### ISSUE TITLE
Package registry doesn't load the package that has accidental .DS_Store file in the root.

### ISSUE THREAD

**Issue by aleksmaus** [elastic/package-registry#672]
Package registry doesn't load the package that has accidental .DS_Store file in the root.
It fails silently and doesn't output any error log. 
It should at least log the cause why the package can't be loaded.

**Comment by ycombinator** [comment]
@aleksmaus, thanks for filing this issue and the corresponding PR to fix it in the package registry.

I'm curious, however, to know what steps you took to load a package with a `.DS_Store` file into the package registry. I checked the `.gitignore` files in all the relevant branches of https://github.com/elastic/package-storage and I see that `.DS_Store` is already mentioned in there. So I assume you ran into this issue while developing and serving a package with the package registry locally? Would you mind posting the steps you took to run into this issue? Perhaps there's tooling we can fix or enhance to detect and clean up such files during local development. Thanks!

**Comment by aleksmaus** [comment]
the prevention you mentioned would be nice, but would not work in my case, because I just browsed to the local packages dir with Finder app (that could create the .DS_Store file) and then it took a bit of time to figure why my package stopped loading. The ```warning``` log message that I added in the PR would be helpful anyways.

**Comment by ycombinator** [comment]
Gotcha. Agreed then that when the package registry loads the package is the earliest time we could catch this issue. Thanks for explaining!
