### ISSUE TITLE
Document how to run EPR in air-gapped environments

### ISSUE THREAD

**Issue by sorantis** [elastic/package-registry#697]
Sometimes in the environments where internet access is not guaranteed (offline/air-gapped) it's not possible to access hosted services. Today our package registry cannot be accessed from air-gapped environments which prevents multiple customer to test/use our new Fleet/Agent capabilities. Since the number of such cases is growing we need to provide a guide that will cover the following 
- set up a private/self-hosted Elastic Package Registry 
- configure Kibana to use the self-hosted registry

**Comment by mtojek** [comment]
This topic comes back as boomerang from time to time. I will write a short doc page on that one.

**Comment by sorantis** [comment]
related: https://github.com/elastic/kibana/issues/77333
