### ISSUE TITLE
Incorrect count for Datastore and Network integrations is displayed on Browse tab under Integrations.

### ISSUE THREAD

**Issue by vipulsrivastava-qasource** [elastic/package-registry#714]
**Kibana version:** 7.14 BC-4 Kibana cloud environment

**Host OS and Browser version:** All, All

**Preconditions:**

1. 7.14.0 BC-4 Kibana cloud environment should be available.

```
Build Details:
Build: 42656
Commit: 82a4f6a7fa23946667599787cdb1b2d82c1d0dfb
```

**Steps to reproduce:**

1. Login to Kibana.
2. Navigate to Integrations-> Browse tab.
3. Click on Datastore integration under Browse by category.
4. Observe that incorrect count is displayed for datastore integration.
5. Now, again click on Network integration under Browse by category
6. Observe that incorrect count is displayed for Network integration.

**Actual Result**
Incorrect count for Datastore and Network integrations is displayed on Browse tab under Integrations.

**Expected Result**
Correct count for Datastore and Network integrations is displayed on Browse tab under Integrations.

**What's working**

- This issue is not occurring for other integration under Browse by category.

**What's not working**
N/A

**Screen Recording**

- **Datastore Integration**
![Datastore](https://user-images.githubusercontent.com/69579402/126942122-d6592556-e6e4-4cfb-99fa-73c3a11f536f.png)

- **Network Integration**
![Network](https://user-images.githubusercontent.com/69579402/126942135-21bf7a04-c929-402f-91da-baf4be840af2.png)

**Comment by kaiyan-sheng** [comment]
Thanks @jen-huang . Does anyone know why when we click a package tile in different locations, the version changes? 
![integrations-version](https://user-images.githubusercontent.com/14081635/130831134-ef79a469-2158-4668-af43-bd6fd89f012c.gif)

**Comment by mtojek** [comment]
> This would show the parent package in more cases, what may change the UX, and it may break things if there are consumers of /search that expect to have always all the policies included in the packages.

I vote for not changing the API behavior for customers. I guess that most people ignores categories and counters in the left pane and simply focus on the search result. We shouldn't filter out results.

> Other option could be to include the categories in the /search response, and Kibana must do the filtering on the client side.

I would prefer this option if we weren't GA, we could simply remove `/categories` endpoint and just include it as "meta" in the search results.

> /categories counts policies and packages separatedly as now, but packages are counted too if they don't match but any of their policies does (for the AWS case this would mean that the count for datastore would be 3: the package and the rds and dynamodb policies, it is 2 now).

I guess this is the most convenient choice. We have to adjust the implementation of categories logic.

**Comment by jsoriano** [comment]
> > /categories counts policies and packages separatedly as now, but packages are counted too if they don't match but any of their policies does (for the AWS case this would mean that the count for datastore would be 3: the package and the rds and dynamodb policies, it is 2 now).
> 
> I guess this is the most convenient choice. We have to adjust the implementation of categories logic.

This alone wouldn't solve the issue of policies not being shown in the search result if their parent packages don't belong to the category.

**Comment by mtojek** [comment]
We had an offline discussion around this with @jsoriano . I will focus on this one.

**Comment by kaiyan-sheng** [comment]
> > I checked the EPR response that Fleet would perform behind the scenes:
> > 
> > * Without category parameter: https://epr-snapshot.elastic.co/search?experimental=true&internal=true&kibana.version=7.15.0
> >   
> >   * Returns AWS 0.10.4
> > * With category parameter: https://epr-snapshot.elastic.co/search?experimental=true&internal=true&kibana.version=7.15.0&category=security
> >   
> >   * Returns AWS 0.8.0
> > 
> > So it looks like EPR is returning different packages when there is a category filter 🤔 Might this be a different or related EPR bug?
> 
> AWS categories were modified in [elastic/integrations#1357](https://github.com/elastic/integrations/pull/1357), ~0.8.0 is probably the latest with the security category~, AWS 0.8.0 includes the security category, but 0.10.4 doesn't, so it doesn't appear in the security category. So the result _is_ correct, maybe we need to rethink how categories work if this is a problem.

Thank you @mtojek and @jsoriano !! Besides the `/categories` endpoint, should we also reconsider if this behavior for `/search` is correct? I don't think we should return different versions for the same package when using the category filter. I probably don't have the full picture here though. Is there a reason why it's returning different versions right now?

**Comment by mtojek** [comment]
I guess this might be a side effect of unset categories for older packages. It's more like a feature than bug :) To prevent this discrepancy we should set exact categories for all.

**Comment by mtojek** [comment]
FYI I'm deploying changes on the snapshot stage.

- `/categories` counts policies and packages separatedly as now, but packages are counted too if they don't match but any of their policies does (for the AWS case this would mean that the count for datastore would be 3: the package and the rds and dynamodb policies, it is 2 now).
- `/search` returns packages with their policies filtered out (for AWS it would return a package with just 2 policies, what would match the count of 3).

**Comment by mtojek** [comment]
I found another bug around `custom`. I suppose it's related to the problem @kaiyan-sheng mentioned. If `category=custom` is present, it will find an older version of `synthetics`, which has the `custom` category. I will try to fix the source code.

Categories API:

```json
  {
    "id": "custom",
    "title": "Custom",
    "count": 4
  },
```

Search API:

```json
[
  {
    "name": "log",
    "title": "Custom logs",
    "version": "0.5.0",
    "release": "experimental",
    "description": "This Elastic integration collects custom logs\n",
    "type": "integration",
    "download": "/epr/log/log-0.5.0.zip",
    "path": "/package/log/0.5.0",
    "icons": [
      {
        "src": "/img/icon.svg",
        "path": "/package/log/0.5.0/img/icon.svg",
        "type": "image/svg+xml"
      }
    ],
    "policy_templates": [
      {
        "name": "logs",
        "title": "Custom logs",
        "description": "Collect your custom log files."
      }
    ]
  },
  {
    "name": "snapshot",
    "title": "Snapshot",
    "version": "0.0.1",
    "release": "beta",
    "description": "Indicator that this is the snapshot distribution",
    "type": "integration",
    "download": "/epr/snapshot/snapshot-0.0.1.zip",
    "path": "/package/snapshot/0.0.1"
  },
  {
    "name": "staging",
    "title": "Staging",
    "version": "0.0.1",
    "release": "beta",
    "description": "Indicator that this is the staging distribution or snapshot",
    "type": "integration",
    "download": "/epr/staging/staging-0.0.1.zip",
    "path": "/package/staging/0.0.1"
  },
  {
    "name": "synthetics",
    "title": "Elastic Synthetics",
    "version": "0.1.0",
    "release": "beta",
    "description": "Monitor services availability.",
    "type": "integration",
    "download": "/epr/synthetics/synthetics-0.1.0.zip",
    "path": "/package/synthetics/0.1.0",
    "icons": [
      {
        "src": "/img/uptime-logo-color-64px.svg",
        "path": "/package/synthetics/0.1.0/img/uptime-logo-color-64px.svg",
        "size": "16x16",
        "type": "image/svg+xml"
      }
    ],
    "policy_templates": [
      {
        "name": "synthetics",
        "title": "Elastic Synthetics",
        "description": "Perform synthetic health checks on network endpoints."
      }
    ]
  },
  {
    "name": "winlog",
    "title": "Custom Windows event logs",
    "version": "0.4.0",
    "release": "experimental",
    "description": "This Elastic integration collects custom Windows event logs",
    "type": "integration",
    "download": "/epr/winlog/winlog-0.4.0.zip",
    "path": "/package/winlog/0.4.0",
    "icons": [
      {
        "src": "/img/logo_windows.svg",
        "path": "/package/winlog/0.4.0/img/logo_windows.svg",
        "type": "image/svg+xml"
      }
    ],
    "policy_templates": [
      {
        "name": "winlogs",
        "title": "Custom Windows event logs",
        "description": "Collect your custom Windows event logs."
      }
    ]
  }
]
```

**Comment by kaiyan-sheng** [comment]
@mtojek Cool!! Thank you so much!!!

**Comment by mtojek** [comment]
Good news! All bugs are gone in the snapshot stage:

<img width="1193" alt="Zrzut ekranu 2021-09-10 o 10 41 37" src="https://user-images.githubusercontent.com/14044910/132826420-0dcf2f8e-935f-45a9-92b6-bae6e8d4639c.png">

<img width="1186" alt="Zrzut ekranu 2021-09-10 o 10 41 47" src="https://user-images.githubusercontent.com/14044910/132826426-b0842e53-6fe6-4e42-b92a-1ae145503323.png">

I will proceed with deployments in staging and production.

**Comment by jsoriano** [comment]
Great, thanks @mtojek!

**Comment by mtojek** [comment]
Everything is merged now.

@vipulsrivastava-qasource Would you mind reverifying the issue?

**Comment by amolnater-qasource** [comment]
Hi @mtojek 
We have revalidated this issue on 7.15.0 Snapshot and found it **fixed** now.
- Count for Datastore, Network and Custom Integrations is showing correct as per available integrations on UI.

**Build details:**
Build: 44006
Commit: 8e250b3e431fe51eea966a0722a691ce70052225

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/133028216-416439dc-5633-41fb-b302-7c5782f28715.JPG)

Hence we are **closing** this issue.
Thanks
