### ISSUE TITLE
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

### ISSUE THREAD

**Issue by mtojek** [elastic/package-registry#723]
@marclop reported a problem with M1 setup (ARM architecture): https://github.com/elastic/elastic-package/issues/497#issuecomment-920840556

```
$ CONTAINER ID   IMAGE          COMMAND            CREATED          STATUS                      PORTS                     NAMES
4d9948f77f82   f32cf92344d6   "/entrypoint.sh"   33 minutes ago   Up 33 minutes (unhealthy)   0.0.0.0:51432->8080/tcp   apm-server_package-registry_1

$ docker logs -n10 apm-server_package-registry_1
2021/09/16 11:16:43 zookeeper           	     1.0.0	/packages/snapshot/zookeeper/1.0.0
2021/09/16 11:16:43 zoom                	     0.5.0	/packages/snapshot/zoom/0.5.0
2021/09/16 11:16:43 zoom                	     0.5.1	/packages/snapshot/zoom/0.5.1
2021/09/16 11:16:43 zscaler             	     0.3.0	/packages/snapshot/zscaler/0.3.0
2021/09/16 11:16:43 zscaler             	     0.3.1	/packages/snapshot/zscaler/0.3.1
2021/09/16 11:16:43 zscaler             	     0.3.2	/packages/snapshot/zscaler/0.3.2
2021/09/16 11:16:43 zscaler             	     0.3.3	/packages/snapshot/zscaler/0.3.3
2021/09/16 11:16:43 Packages in /packages/local:
2021/09/16 11:16:43 apm                 	     0.5.0	/packages/local/apm/0.5.0
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

$ uname -a
Darwin REDACTED 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64
```

It looks like Package Registry (Go application) doesn't play well with arm64 emulated with qemu.

**Comment by aspacca** [comment]
I've tested with the following setup and worked properly:
```
$ uname -a
Darwin REDACTED 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64

$ docker --version
Docker version 20.10.8, build 3967b7d

docker desktop
Version 4.0.0 (67817)
Engine: 20.10.8
Credential Helper: 0.6.5
Snyk: v1.563.0
Compose: 1.29.2
Kubernetes: v1.21.4
```

I got the following warning from docker:
```
The requested image's platform (linux/amd64) does not match the detected host plaform (linux/arm64/v8) and no specific plaform was requested
```

**Comment by marclop** [comment]
Kind of embarrassing but it turns out that I had forgotten to install rosetta on my M1 MacBook, made the package registry work:

```
$ softwareupdate --install-rosetta
```

**Comment by jlind23** [comment]
@marclop Should I close this issue as you do not have anymore problems?

**Comment by marclop** [comment]
yeah, let's close this up.

**Comment by mtojek** [comment]
We had a chat with @marclop today, that apparently he still faces such issues. It might be good to build the ARM image for Package Registry and check if the situation improves, so let's keep this issue open or create another one to build Package Registry container image for ARM arch.

**Comment by mrodm** [comment]
> The requested image's platform (linux/amd64) does not match the detected host plaform (linux/arm64/v8) and no specific plaform was requested

> It might be good to build the ARM image for Package Registry and check if the situation improves, so let's keep this issue open or create another one to build Package Registry container image for ARM arch.

Closing this issue since the support for Package-Registry container images as a multi-platform one (linux/amd64 and linux/arm64) was added in https://github.com/elastic/package-registry/pull/1162 and those docker images are already used in the Elastic stack started by `elastic-package`.
