### ISSUE TITLE
Add signatures to integration packages for validation

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/package-registry#726]
We must add signatures to all of our packages so that Kibana could check the sanity of the integration packages loaded and presented to the users. Kibana loads packages with Superuser permissions. If a bad package is uploaded into Kibana, it can have costly repercussions. From the security point of view, it's a big loophole in our system.

**Comment by mtojek** [comment]
I guess we have at least two other issues referring to this problem.

https://github.com/elastic/package-spec/issues/46
https://github.com/elastic/package-registry/issues/168

It might be good to unify this (mark duplicates) and keep the idea in the package-spec.

**Comment by jlind23** [comment]
Closed following @mtojek comment
