### ISSUE TITLE
JSON responses contain key with dot in 'kibana.version'

### ISSUE THREAD

**Issue by andrewkroh** [elastic/package-registry#730]
The response from the `/package` endpoint uses a key name that contains a dot. It's not common to use field names that contain dots and this might lead to confusion when processing the response data. For example the `elastic-package` tool would not [unmarshal this field](https://github.com/elastic/elastic-package/blob/a0a7defd0db574d36924b52bf6fe5dce899d9f74/internal/packages/packages.go#L78-L81) if it were returned.

Example: https://epr.elastic.co/package/gcp/1.1.0/

```
  "conditions": {
    "kibana.version": "^7.15.0"
  },
```

My preferred representation would be

```
  "conditions": {
    "kibana": {
      "version": "^7.15.0"
    }
  },
```

It should be easy to fix the package-registry, but changing it could break clients. So are there any clients using this field? I can check Kibana, but is that the only user?

**Comment by andrewkroh** [comment]
I did a search in Kibana and didn't find anything reading the value. Probably it has not need to read the value because it can query using `?kibana.version` and receive results that are already filtered.

**Comment by ruflin** [comment]
I assume you are right but lets @joshdover confirm it. There are some scripts that use the API but I doubt any of these uses the "output" value at the moment.
