### ISSUE TITLE
Replace Package Storage with object storage (S3,GCP, ..).

### ISSUE THREAD

**Issue by jlind23** [elastic/package-registry#771]
Depends on https://github.com/elastic/package-storage/issues/2774

**Comment by jlind23** [comment]
@mtojek which one should we aim first?

**Comment by mtojek** [comment]
Do you mean S3 or GCP?

That would be an outcome of https://github.com/elastic/package-storage/issues/2774. Right now I'm working on the short design doc to define our requirements and pick the right solution (see @cachedout 's comment in the issue).

**Comment by jlind23** [comment]
Great!

**Comment by cachedout** [comment]
> Do you mean S3 or GCP?

I can wait for the design doc to comment further, but if it's helpful when writing that doc, you should know that we're pretty heavily biased toward GCP buckets in terms of our existing deployments. 

We could potentially do a S3 bucket if that's truly what you need but there are some unresolved issues that we're working through with a different team around the use of S3. You can see further context here if it's of interest: https://github.com/elastic/infra/issues/33117

**Comment by mtojek** [comment]
It's more about being cloud provider agnostic, but I agree that we should preserve consistency with other solutions we host.

**Comment by jlind23** [comment]
Not relevant anymore.
