### ISSUE TITLE
Deprecation path of the Package Storage v1.

### ISSUE THREAD

**Issue by jlind23** [elastic/package-registry#772]

**Comment by jlind23** [comment]
@mtojek @jsoriano Can the package registry API target both storage layers?
The V2 must be checked first but if a package does not exist then we will check if it exists against the V1 storage layer?
Doing so will allow us having those two storage layers working in parallel for a given period of time before thinking about shutting down the V1.
At the same time, publishing a new package must be enable only on the V2 layer which means:
- [ ] Updating Elastic package in order to push only to this new registry
- [ ] Disabling package storage write permissions for developers
- [ ] Updating package registry API in a non breaking way

Am I missing something?

**Comment by jsoriano** [comment]
I think we shouldn't deprecate current storage, being able to run the package registry with local storage still has its applications, as running in air-gapped or other custom environments, or for development purposes.

We will need to add some settings to select what storage (and/or indexer) is used.

> Can the package registry API target both storage layers?
> The V2 must be checked first but if a package does not exist then we will check if it exists against the V1 storage layer?

If we continue with the existing "indexers" pattern, we could add another indexer ([here](https://github.com/elastic/package-registry/blob/main/main.go#L126-L129)) and on a first release continue including the V1 storage in the image.

But I think we shouldn't be so worried about missing packages in the V2 storage, this is the "easy" part. More complicated will be to check that the registry using the V2 storage generates the same responses as when using the V1 storage. Keeping the changes below the current indexer abstraction will probably help on maintaining the API.

> Doing so will allow us having those two storage layers working in parallel for a given period of time before thinking about shutting down the V1.

I think that ideally we should have both registries running at the same time, and do some kind of A/B deployment, sending a small percentage of requests to the new registry at the beginning and confirming that nothing breaks, and then eventually replace the V1 deployment. We will have to check what options we have to do this with our current infra. A challenge of this approach is that we are not going to be able to guarantee that both storages are synced, so maybe we need per-client routing for consistency, what can limit the options.

If we check the v2 storage first, then we are doing a full replacement at once (unless we intentionally don't deploy all packages in the V2 storage, so only some packages are served from there). But this may be fine if we are sure that the new registry behaves as the old one.

>  At the same time, publishing a new package must be enable only on the V2 layer which means:

I think that during some time we should continue publishing to both storages if possible, this will allow to do a smoother migration, or to roll-back if needed.

**Comment by mtojek** [comment]
> I think we shouldn't deprecate current storage, being able to run the package registry with local storage still has its applications, as running in air-gapped or other custom environments, or for development purposes.

I think that you mixed Package Registry and Package Storage v1.  I agree that we will still need to build Docker images for Package Storage, exactly for air-gapped environments. For development purposes, there will be a local package discovery (that would work similarly to a static HTTP server + search endpoint).

We can use packages stored in v2 to bake those Docker images and even consider multiple different distributions that a single "production".

> More complicated will be to check that the registry using the V2 storage generates the same responses as when using the V1 storage.

If we want to achieve a strict level of consistency, we can jump over all packages (~1000, not much) and simply compare all HTTP responses :)

**Comment by jsoriano** [comment]
> I think that you mixed Package Registry and Package Storage v1.

I only wanted to be clear about continuing supporting current local storage. At the end this issue is open in the package registry repo :)

> For development purposes, there will be a local package discovery (that would work similarly to a static HTTP server + search endpoint).

Is this different to current local storage? Or this would be a new "transparent" or "auto-updated" local indexer? This would be a different effort.

> We can use packages stored in v2 to bake those Docker images and even consider multiple different distributions that a single "production".

+1, we will need to update the job tagging distributions if we stop updating the v1 registry.

> If we want to achieve a strict level of consistency, we can jump over all packages (~1000, not much) and simply compare all HTTP responses :)

SGTM :) We can prepare a list of requests and compare results before doing the swap.

**Comment by mtojek** [comment]
> Is this different to current local storage? Or this would be a new "transparent" or "auto-updated" local indexer? This would be a different effort.

Yes, it would be more advanced. We included it in the v2 presentation:

https://docs.google.com/presentation/d/17wNMO7Z_z85JeQ0UX8kjGO_b48vodqy_0RiV1VofDlM/edit#slide=id.gcfb74501f8_0_50

**Comment by jsoriano** [comment]
Ah yes, the auto-discovery mode, but this can be done later, right?

**Comment by mtojek** [comment]
It isn't critical but seems to be a nice improvement for people with air-gapped environments. For example, you could copy another .zip package to the shared volume and all corp instances of EPR will just auto-discover and serve the file, without any restarts.

Anyway, do you think we should note all the next steps until rollout in a Google doc? We could discuss the entire process.

**Comment by jlind23** [comment]
> Anyway, do you think we should note all the next steps until rollout in a Google doc? We could discuss the entire process.

Yes we should, this will be our todo list and doing so will avoid missing something while migrating.

**Comment by jsoriano** [comment]
> It isn't critical but seems to be a nice improvement for people with air-gapped environments. For example, you could copy another .zip package to the shared volume and all corp instances of EPR will just auto-discover and serve the file, without any restarts.

Yes, but I think this is a separated thing, we can do this independently of the storage v2.

**Comment by mtojek** [comment]
I think we covered the overall plan with this [document](https://docs.google.com/document/d/10PZFL8-VIiK73kXygLrNzvzld8cWqNQUSThsRUl_vRI/edit#heading=h.xbs7krnt5hku).

**Comment by jlind23** [comment]
Closing for now following this comment https://github.com/elastic/package-registry/issues/772#issuecomment-1108454827
