### ISSUE TITLE
Packages are immutable

### ISSUE THREAD

**Issue by jlind23** [elastic/package-registry#782]
Packages are immutable, the end-user can’t modify their resources (dashboards, visualizations, pipelines), but can create a copy.

**Comment by jlind23** [comment]
@mtojek this is a two phase issue i think.
1. Packages should not be accepted by kibana if users update them after download. Which means that kibana should be able to revalidate package content
2. Package-storage branches should be protected and the only way of modifying a package is creating a new version of it

What do you think? Is there any missing pieces?

**Comment by mtojek** [comment]
> Packages should not be accepted by kibana if users update them after download. Which means that kibana should be able to revalidate package content

This is a good question to @jen-huang. Once a package is installed, so its resources have been pushed to either Elasticsearch or Kibana, is Kibana aware which resource belongs to which package?

> Package-storage branches should be protected and the only way of modifying a package is creating a new version of it

Once we introduce the true object storage, I don't think this would be possible. There is a risk that the end-user creates an altered copy locally, close to the Package Registry application, but then the package signature won't be matching (package should be rejected.

**Comment by jen-huang** [comment]
(Sorry for late reply - this got lost in my notifications!)

> Once a package is installed, so its resources have been pushed to either Elasticsearch or Kibana, is Kibana aware which resource belongs to which package?

Yes, for installed packages, Fleet keeps a track of all of its associated assets.

For ES assets, Fleet currently adds `managed` metadata (`_meta` field) to distinguish that these ought to be immutable assets. Soon, we will also be adding similar metadata to Kibana assets (https://github.com/elastic/kibana/issues/123904). Note that this work doesn't actually enforce immutability of these assets yet, just lays the groundwork for identifying them.

**Comment by jlind23** [comment]
[Clean up] Closing this as outdated, will reopen if required.
