### ISSUE TITLE
package-registry observability integration

### ISSUE THREAD

**Issue by jsoriano** [elastic/package-registry#797]
Add integration to observe deployments of the package registry. This integration could collect metrics and logs, and provide dashboards. It could also link to APM data.

- [x] Add metrics endpoint https://github.com/elastic/package-registry/pull/827
- [x] Update elastic-package stack to expose metrics endpoint https://github.com/elastic/elastic-package/pull/885
- [x] Add a new integration for Elastic Package Registry 
    - Metrics and Dashboards https://github.com/elastic/integrations/pull/3671
    - Elastic Package Registry logo https://github.com/elastic/integrations/pull/3880
    - Update favicon in Package Registry service https://github.com/elastic/package-registry/pull/858

**Comment by akshay-saraswat** [comment]
[Product Requirements Doc](https://docs.google.com/document/d/1C7_gs25Sb9lmv7YlC0Ff1vHAp6_VMqgOknhiWtb9Cj8)

**Comment by jlind23** [comment]
Closing it as all issues are done.
