### ISSUE TITLE
Implement the indexing job

### ISSUE THREAD

**Issue by jlind23** [elastic/package-registry#799]
As part of the new package storage architecture, we should implement the indexing job for the new storage.

**Comment by mtojek** [comment]
Let me write more details about this issue. We'd like to create the following structure:

```
└── v2
    └── metadata
        ├── 1637150104
        ├── 1637150105
        ├── 1637150106
        │   ├── search-index-all.yml
        │   └── … (other indices)
        └── cursor.yml
```

`cursor.yml` - points to the last `metadata/<timestamp`>
`search-index-all.yml` - contains entries for packages listed with [search?all=1](https://epr.elastic.co/search?all=1)
_(other indices)_ - I don't think we need anything here right now.

Modified Package Registry will keep watching the cursor file and in case of updates, it will download new indices.

**Comment by mtojek** [comment]
The only part we need to discuss is the way to create the main index, `search-index-all.yml`.

The indexing job is triggered by a successful publishing job. The publishing job doesn't have to wait, as the process is asynchronous. Here are the possible options:

A. The indexing job opens/downloads every package.zip file, extracts the `manifest.yml` file, and combines it together into a big `search-index-all.yml` file. If the file is different from the last timestamp metadata, it will update the reference.
 
Pros:
* whenever we trigger it, we can be sure that all packages will be included in the index

Cons:
* indexing takes time, the job needs to download all .zip files
* doesn't scale well, most likely we'll have to revisit it later

B. The indexing job receives a link to the extracted `manifest.yml` file by the publishing job. It will read only this file and prepare a new index file.

Pros:
* indexing is quicker than revisiting all packages and re-writing from scratches the entire index.

Cons:
* if we lose an "indexing" request, we still need to re-index all files

C. This would be a mix of A. and B. The indexing job is reading the last `search-index-all.yml` first, then discovers which .zip files have been added, downloads the relevant files, extracts manifest, creates a new index.

Pros:
* doable and easy to implement as first step or MVP
* for single packages, the indexing will be relatively quick
* we don't need to care about lost "indexing events" or interrupted jobs
* even if we start pushing big packages (1-2 GB), it won't be a problem to finish the job in a short time.

Cons:
* the first run would be a long execution

---

My preference is option C. as it seems to be rather predictable and easy to deliver. @jsoriano WDYT?

**Comment by jsoriano** [comment]
@mtojek yes, I also like option C, no worries about the first run :slightly_smiling_face:

An optimization could be to include the list of published packages in the notification sent from the publisher to the indexer, so we don't need to read the whole storage to find new packages. Though we would need to do it in any case from time to time if we cannot guarantee that all notifications are received at least once.

We will also need to detect deleted packages and remove them from the index. Even if this is something we don't want to support in the usual processes, we may need to do it for reasons of _force majeure_.
Though we can do this in a later stage, worst case packages deleted from the storage will produce some 404s.
