### ISSUE TITLE
How to disable TLS version 1.0 and 1.1?

### ISSUE THREAD

**Issue by hwxy233** [elastic/package-registry#965]
Hi, I'm running the `package-registry` with `podman` on linux server in an air-gapped environment.
Recently, due to the company's regulations, I need to disable TLS version 1.0 and 1.1. 
I read this doc [Air-gapped environments](https://www.elastic.co/guide/en/fleet/8.4/air-gapped.html#air-gapped) but I can't find a way to disable or use some TLS versions.
So I want to ask is there a way to enable or disable some TLS versions? Thanks.

The whole Elastic Stack version is `8.4`.
I run `package-registry` use this command:
```bash
podman run -itd -p 2443:443 \
  --volume /etc/ssl/package-registry.key:/etc/ssl/package-registry.key:ro \
  --volume /etc/ssl/package-registry.crt:/etc/ssl/package-registry.pem:ro \
  --name elastic-package-registry \
  --health-cmd "curl -f -L https://`hostname`:2443" \
  -e EPR_ADDRESS=0.0.0.0:443 \
  -e EPR_TLS_KEY=/etc/ssl/package-registry.key \
  -e EPR_TLS_CERT=/etc/ssl/package-registry.pem \
  docker.elastic.co/package-registry/distribution:8.4.3
```

**Update** by @jsoriano: To support this we would need to add something like a `-tls-min-version` flag, that would accept values from `"1.0"` to `"1.3"`, and would translate to the `MinVersion` attribute in the [`tls.Config`](https://pkg.go.dev/crypto/tls#Config) of the http server. If not set, it should continue using the Go runtime defaults. Adding the `tls-min-version` flag will also add the `EPR_TLS_MIN_VERSION` environment variable, setting it to `1.2` would solve this use case.

**Comment by jsoriano** [comment]
Hey @chengye233,

It is currently not possible to configure the set of ciphers or the range of TLS versions supported by `package-registry`. We rely on the Go runtime defaults, which use to be secure enough.

It'd be good though to expose [`MinVersion`](https://pkg.go.dev/crypto/tls#Config) as a configurable parameter to support these scenarios. I will add this to our backlog.

Thanks for your question.
